///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WakeApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddAlarm recording.
    /// </summary>
    [TestModule("5e532534-a94a-4aa3-ab35-078ccc867a1e", ModuleType.Recording, 1)]
    public partial class AddAlarm : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WakeAppRepository repository.
        /// </summary>
        public static WakeAppRepository repo = WakeAppRepository.Instance;

        static AddAlarm instance = new AddAlarm();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddAlarm()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddAlarm Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DivTagRow.SomeTdTag' at 13;8.", repo.WelcomeWakeApp.DivTagRow.SomeTdTagInfo, new RecordItemIndex(0));
            repo.WelcomeWakeApp.DivTagRow.SomeTdTag.Click("13;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DivTagRow.ATag1' at LowerRight.", repo.WelcomeWakeApp.DivTagRow.ATag1Info, new RecordItemIndex(1));
            repo.WelcomeWakeApp.DivTagRow.ATag1.Click(Location.LowerRight);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DivTagRow.ATagDodaj1' at 47;22.", repo.WelcomeWakeApp.DivTagRow.ATagDodaj1Info, new RecordItemIndex(2));
            repo.WelcomeWakeApp.DivTagRow.ATagDodaj1.Click("47;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DateStart' at 308;21.", repo.WelcomeWakeApp.DateStartInfo, new RecordItemIndex(3));
            repo.WelcomeWakeApp.DateStart.Click("308;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 193;230.", repo.Dropdown.SelfInfo, new RecordItemIndex(4));
            repo.Dropdown.Self.Click("193;230");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.Repeat' at 8;8.", repo.WelcomeWakeApp.RepeatInfo, new RecordItemIndex(5));
            repo.WelcomeWakeApp.Repeat.Click("8;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.Monday' at 9;9.", repo.WelcomeWakeApp.MondayInfo, new RecordItemIndex(6));
            repo.WelcomeWakeApp.Monday.Click("9;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.Wednesday' at 6;6.", repo.WelcomeWakeApp.WednesdayInfo, new RecordItemIndex(7));
            repo.WelcomeWakeApp.Wednesday.Click("6;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DateEnd' at 25;23.", repo.WelcomeWakeApp.DateEndInfo, new RecordItemIndex(8));
            repo.WelcomeWakeApp.DateEnd.Click("25;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad2 up}{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad2 up}' with focus on 'WelcomeWakeApp.DateEnd'.", repo.WelcomeWakeApp.DateEndInfo, new RecordItemIndex(9));
            repo.WelcomeWakeApp.DateEnd.PressKeys("{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad2 up}{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad2 up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'WelcomeWakeApp.DateEnd'.", repo.WelcomeWakeApp.DateEndInfo, new RecordItemIndex(10));
            repo.WelcomeWakeApp.DateEnd.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad2}{NumPad2}{NumPad2}' with focus on 'WelcomeWakeApp.DateEnd'.", repo.WelcomeWakeApp.DateEndInfo, new RecordItemIndex(11));
            repo.WelcomeWakeApp.DateEnd.PressKeys("{NumPad2}{NumPad2}{NumPad2}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.Comment' at 96;32.", repo.WelcomeWakeApp.CommentInfo, new RecordItemIndex(12));
            repo.WelcomeWakeApp.Comment.Click("96;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'WelcomeWakeApp.Comment'.", repo.WelcomeWakeApp.CommentInfo, new RecordItemIndex(13));
            repo.WelcomeWakeApp.Comment.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DivTagRow.Submit2' at 40;16.", repo.WelcomeWakeApp.DivTagRow.Submit2Info, new RecordItemIndex(14));
            repo.WelcomeWakeApp.DivTagRow.Submit2.Click("40;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Proszę wybrać datę zakończenia nie wcześniejszą niż data rozpoczęcia') on item 'WelcomeWakeApp.DivTagRow.ProszęWybraćDatęZakończeniaNieWcześ'.", repo.WelcomeWakeApp.DivTagRow.ProszęWybraćDatęZakończeniaNieWcześInfo, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.WelcomeWakeApp.DivTagRow.ProszęWybraćDatęZakończeniaNieWcześInfo, "InnerText", "Proszę wybrać datę zakończenia nie wcześniejszą niż data rozpoczęcia");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DateEnd' at 22;23.", repo.WelcomeWakeApp.DateEndInfo, new RecordItemIndex(16));
            repo.WelcomeWakeApp.DateEnd.Click("22;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DateEnd' at 72;19.", repo.WelcomeWakeApp.DateEndInfo, new RecordItemIndex(17));
            repo.WelcomeWakeApp.DateEnd.Click("72;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad2}{NumPad0}{NumPad2}{NumPad1}' with focus on 'WelcomeWakeApp.DateEnd'.", repo.WelcomeWakeApp.DateEndInfo, new RecordItemIndex(18));
            repo.WelcomeWakeApp.DateEnd.PressKeys("{NumPad2}{NumPad0}{NumPad2}{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DivTagRow.Submit2' at 44;19.", repo.WelcomeWakeApp.DivTagRow.Submit2Info, new RecordItemIndex(19));
            repo.WelcomeWakeApp.DivTagRow.Submit2.Click("44;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DivTagRow.Submit2' at 43;17.", repo.WelcomeWakeApp.DivTagRow.Submit2Info, new RecordItemIndex(20));
            repo.WelcomeWakeApp.DivTagRow.Submit2.Click("43;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\n                        test\n                    ') on item 'WelcomeWakeApp.DivTagRow.TdTagTest'.", repo.WelcomeWakeApp.DivTagRow.TdTagTestInfo, new RecordItemIndex(21));
            Validate.AttributeEqual(repo.WelcomeWakeApp.DivTagRow.TdTagTestInfo, "InnerText", "\n                        test\n                    ");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
