///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WakeApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddDevice recording.
    /// </summary>
    [TestModule("3e5cbe22-a4f8-4d2e-b9fa-273d92380733", ModuleType.Recording, 1)]
    public partial class AddDevice : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AddDeviceArduino repository.
        /// </summary>
        public static AddDeviceArduino repo = AddDeviceArduino.Instance;

        static AddDevice instance = new AddDevice();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddDevice()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddDevice Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.ButtonTag1' at 16;11.", repo.WelcomeWakeApp.ButtonTag1Info, new RecordItemIndex(0));
            repo.WelcomeWakeApp.ButtonTag1.Click("16;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp' at 294;243.", repo.WelcomeWakeApp.SelfInfo, new RecordItemIndex(1));
            repo.WelcomeWakeApp.Self.Click("294;243");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.Name' at 38;15.", repo.WelcomeWakeApp.NameInfo, new RecordItemIndex(2));
            repo.WelcomeWakeApp.Name.Click("38;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Arduino' with focus on 'WelcomeWakeApp.Name'.", repo.WelcomeWakeApp.NameInfo, new RecordItemIndex(3));
            repo.WelcomeWakeApp.Name.PressKeys("Arduino");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.InputTagMac' at 60;17.", repo.WelcomeWakeApp.InputTagMacInfo, new RecordItemIndex(4));
            repo.WelcomeWakeApp.InputTagMac.Click("60;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'mac' with focus on 'WelcomeWakeApp.InputTagMac'.", repo.WelcomeWakeApp.InputTagMacInfo, new RecordItemIndex(5));
            repo.WelcomeWakeApp.InputTagMac.PressKeys("mac");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DivTagRow.Submit1' at 35;18.", repo.WelcomeWakeApp.DivTagRow.Submit1Info, new RecordItemIndex(6));
            repo.WelcomeWakeApp.DivTagRow.Submit1.Click("35;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'WelcomeWakeApp.DivTagRow.TdTag1'.", repo.WelcomeWakeApp.DivTagRow.TdTag1Info, new RecordItemIndex(7));
            Validate.Exists(repo.WelcomeWakeApp.DivTagRow.TdTag1Info);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
