///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WakeApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddPhone recording.
    /// </summary>
    [TestModule("cfdd0209-8bfa-4e35-85dc-2be7b7315b93", ModuleType.Recording, 1)]
    public partial class AddPhone : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WakeAppRepository repository.
        /// </summary>
        public static WakeAppRepository repo = WakeAppRepository.Instance;

        static AddPhone instance = new AddPhone();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddPhone()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddPhone Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.FaFaPlus' at 6;7.", repo.WelcomeWakeApp.FaFaPlusInfo, new RecordItemIndex(0));
            repo.WelcomeWakeApp.FaFaPlus.Click("6;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp' at 340;258.", repo.WelcomeWakeApp.SelfInfo, new RecordItemIndex(1));
            repo.WelcomeWakeApp.Self.Click("340;258");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Phone' with focus on 'WelcomeWakeApp'.", repo.WelcomeWakeApp.SelfInfo, new RecordItemIndex(2));
            repo.WelcomeWakeApp.Self.EnsureVisible();
            Keyboard.Press("Phone");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.InputTagMac' at 52;15.", repo.WelcomeWakeApp.InputTagMacInfo, new RecordItemIndex(3));
            repo.WelcomeWakeApp.InputTagMac.Click("52;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}+{RShiftKey up}48792215483' with focus on 'WelcomeWakeApp.InputTagMac'.", repo.WelcomeWakeApp.InputTagMacInfo, new RecordItemIndex(4));
            repo.WelcomeWakeApp.InputTagMac.PressKeys("{RShiftKey down}+{RShiftKey up}48792215483");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'telefon' on item 'WelcomeWakeApp.DeviceType'.", repo.WelcomeWakeApp.DeviceTypeInfo, new RecordItemIndex(5));
            repo.WelcomeWakeApp.DeviceType.Element.SetAttributeValue("TagValue", "telefon");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DivTagRow.Submit1' at 35;19.", repo.WelcomeWakeApp.DivTagRow.Submit1Info, new RecordItemIndex(6));
            repo.WelcomeWakeApp.DivTagRow.Submit1.Click("35;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\n                                    Phone\n                                ') on item 'WelcomeWakeApp.DivTagRow.SomeTdTag'.", repo.WelcomeWakeApp.DivTagRow.SomeTdTagInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.WelcomeWakeApp.DivTagRow.SomeTdTagInfo, "InnerText", "\n                                    Phone\n                                ");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
