///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WakeApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Alarm recording.
    /// </summary>
    [TestModule("685f952c-c909-4665-a41c-c66490a91424", ModuleType.Recording, 1)]
    public partial class Alarm : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WakeAppRepository repository.
        /// </summary>
        public static WakeAppRepository repo = WakeAppRepository.Instance;

        static Alarm instance = new Alarm();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Alarm()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Alarm Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DivTagRow.ATag1' at 52;16.", repo.WelcomeWakeApp.DivTagRow.ATag1Info, new RecordItemIndex(0));
            repo.WelcomeWakeApp.DivTagRow.ATag1.Click("52;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DivTagRow.ATagDodaj1' at 32;16.", repo.WelcomeWakeApp.DivTagRow.ATagDodaj1Info, new RecordItemIndex(1));
            repo.WelcomeWakeApp.DivTagRow.ATagDodaj1.Click("32;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp' at 314;479.", repo.WelcomeWakeApp.SelfInfo, new RecordItemIndex(2));
            repo.WelcomeWakeApp.Self.Click("314;479");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.Tuesday' at 7;0.", repo.WelcomeWakeApp.TuesdayInfo, new RecordItemIndex(3));
            repo.WelcomeWakeApp.Tuesday.Click("7;0");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DateEnd' at 26;17.", repo.WelcomeWakeApp.DateEndInfo, new RecordItemIndex(4));
            repo.WelcomeWakeApp.DateEnd.Click("26;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad2 up}{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad2 up}{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad2 up}{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad2 up}' with focus on 'WelcomeWakeApp.DateEnd'.", repo.WelcomeWakeApp.DateEndInfo, new RecordItemIndex(5));
            repo.WelcomeWakeApp.DateEnd.PressKeys("{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad2 up}{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad2 up}{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad2 up}{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad2 up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.Comment' at 47;23.", repo.WelcomeWakeApp.CommentInfo, new RecordItemIndex(6));
            repo.WelcomeWakeApp.Comment.Click("47;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad2 up}' with focus on 'WelcomeWakeApp.Comment'.", repo.WelcomeWakeApp.CommentInfo, new RecordItemIndex(7));
            repo.WelcomeWakeApp.Comment.PressKeys("{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad2 up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DivTagRow.Submit2' at 36;20.", repo.WelcomeWakeApp.DivTagRow.Submit2Info, new RecordItemIndex(8));
            repo.WelcomeWakeApp.DivTagRow.Submit2.Click("36;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Proszę wybrać datę zakończenia nie wcześniejszą niż data rozpoczęcia') on item 'WelcomeWakeApp.DivTagRow.ProszęWybraćDatęZakończeniaNieWcześ'.", repo.WelcomeWakeApp.DivTagRow.ProszęWybraćDatęZakończeniaNieWcześInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.WelcomeWakeApp.DivTagRow.ProszęWybraćDatęZakończeniaNieWcześInfo, "InnerText", "Proszę wybrać datę zakończenia nie wcześniejszą niż data rozpoczęcia");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.Comment' at 52;41.", repo.WelcomeWakeApp.CommentInfo, new RecordItemIndex(10));
            repo.WelcomeWakeApp.Comment.Click("52;41");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DateEnd' at 83;19.", repo.WelcomeWakeApp.DateEndInfo, new RecordItemIndex(11));
            repo.WelcomeWakeApp.DateEnd.Click("83;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad2 down}{NumPad1 down}{NumPad2 up}{NumPad1 up}{NumPad2 down}{NumPad1 down}{NumPad2 up}{NumPad1 up}' with focus on 'WelcomeWakeApp.DateEnd'.", repo.WelcomeWakeApp.DateEndInfo, new RecordItemIndex(12));
            repo.WelcomeWakeApp.DateEnd.PressKeys("{NumPad2 down}{NumPad1 down}{NumPad2 up}{NumPad1 up}{NumPad2 down}{NumPad1 down}{NumPad2 up}{NumPad1 up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.Comment' at 70;53.", repo.WelcomeWakeApp.CommentInfo, new RecordItemIndex(13));
            repo.WelcomeWakeApp.Comment.Click("70;53");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DivTagRow.Submit2' at 45;10.", repo.WelcomeWakeApp.DivTagRow.Submit2Info, new RecordItemIndex(14));
            repo.WelcomeWakeApp.DivTagRow.Submit2.Click("45;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\n                        12\n                    ') on item 'WelcomeWakeApp.DivTagRow.TdTag'.", repo.WelcomeWakeApp.DivTagRow.TdTagInfo, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.WelcomeWakeApp.DivTagRow.TdTagInfo, "InnerText", "\n                        12\n                    ");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
