///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WakeApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckErrorMessages recording.
    /// </summary>
    [TestModule("bc8a9c5e-24ad-46d9-ba77-0a976762a8f1", ModuleType.Recording, 1)]
    public partial class CheckErrorMessages : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WakeAppRepository repository.
        /// </summary>
        public static WakeAppRepository repo = WakeAppRepository.Instance;

        static CheckErrorMessages instance = new CheckErrorMessages();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckErrorMessages()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckErrorMessages Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.projektbudzik.pl/Contact?' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://www.projektbudzik.pl/Contact?", "Chrome", "", false, false, false, true, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(1));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.DivTagRow.Wyślij' at 28;12.", repo.WelcomeWakeApp.DivTagRow.WyślijInfo, new RecordItemIndex(2));
            repo.WelcomeWakeApp.DivTagRow.Wyślij.Click("28;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Imię jest wymagane') on item 'WelcomeWakeApp.NameError'.", repo.WelcomeWakeApp.NameErrorInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.WelcomeWakeApp.NameErrorInfo, "InnerText", "Imię jest wymagane");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Email jest wymagany') on item 'WelcomeWakeApp.EmailError'.", repo.WelcomeWakeApp.EmailErrorInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.WelcomeWakeApp.EmailErrorInfo, "InnerText", "Email jest wymagany");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Temat jest wymagany') on item 'WelcomeWakeApp.SubjectError'.", repo.WelcomeWakeApp.SubjectErrorInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.WelcomeWakeApp.SubjectErrorInfo, "InnerText", "Temat jest wymagany");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Treść wiadomości jest wymagana') on item 'WelcomeWakeApp.MessageError'.", repo.WelcomeWakeApp.MessageErrorInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.WelcomeWakeApp.MessageErrorInfo, "InnerText", "Treść wiadomości jest wymagana");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'WelcomeWakeApp.DivTagRow.ColMd4'.", repo.WelcomeWakeApp.DivTagRow.ColMd4Info, new RecordItemIndex(7));
            Validate.Exists(repo.WelcomeWakeApp.DivTagRow.ColMd4Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Godziny pracy:') on item 'WelcomeWakeApp.DivTagRow.GodzinyPracy'.", repo.WelcomeWakeApp.DivTagRow.GodzinyPracyInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.WelcomeWakeApp.DivTagRow.GodzinyPracyInfo, "InnerText", "Godziny pracy:");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Wsparcie Techniczne:') on item 'WelcomeWakeApp.DivTagRow.WsparcieTechniczne'.", repo.WelcomeWakeApp.DivTagRow.WsparcieTechniczneInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.WelcomeWakeApp.DivTagRow.WsparcieTechniczneInfo, "InnerText", "Wsparcie Techniczne:");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Application", "Killing application containing item 'WelcomeWakeApp'.", repo.WelcomeWakeApp.SelfInfo, new RecordItemIndex(10));
            Host.Current.KillApplication(repo.WelcomeWakeApp.Self);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
