///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WakeApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MobileWebsite recording.
    /// </summary>
    [TestModule("42797f65-7b53-484c-b204-221b7e19d02c", ModuleType.Recording, 1)]
    public partial class MobileWebsite : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WakeAppRepository repository.
        /// </summary>
        public static WakeAppRepository repo = WakeAppRepository.Instance;

        static MobileWebsite instance = new MobileWebsite();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MobileWebsite()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MobileWebsite Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'ranorex.RxBrowser' on device " + Ranorex.Core.Remoting.RemoteServiceLocator.GetCurrentDeviceName() + ".", new RecordItemIndex(0));
            Host.Local.RunMobileApp(Ranorex.Core.Remoting.RemoteServiceLocator.GetCurrentDeviceName(), "ranorex.RxBrowser", true);
            Delay.Milliseconds(3500);
            
            // Browse to site.
            Report.Log(ReportLevel.Info, "Set value", "Browse to site.\r\nSetting attribute PageUrl to 'http://www.projektbudzik.pl/Account/Login?' on item 'Browser.Dom'.", repo.Browser.Dom.SelfInfo, new RecordItemIndex(1));
            repo.Browser.Dom.Self.Element.SetAttributeValue("PageUrl", "http://www.projektbudzik.pl/Account/Login?");
            Delay.Milliseconds(10000);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Browser.Dom.Email' at Center", repo.Browser.Dom.EmailInfo, new RecordItemIndex(2));
            repo.Browser.Dom.Email.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to 'test1@gmail.com' on item 'Browser.Dom.Email'.", repo.Browser.Dom.EmailInfo, new RecordItemIndex(3));
            repo.Browser.Dom.Email.Element.SetAttributeValue("Value", "test1@gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Browser.Dom.Password' at Center", repo.Browser.Dom.PasswordInfo, new RecordItemIndex(4));
            repo.Browser.Dom.Password.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to 'WakeApp132!' on item 'Browser.Dom.Password'.", repo.Browser.Dom.PasswordInfo, new RecordItemIndex(5));
            repo.Browser.Dom.Password.Element.SetAttributeValue("Value", "WakeApp132!");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Browser.Dom.Submit' at Center", repo.Browser.Dom.SubmitInfo, new RecordItemIndex(6));
            repo.Browser.Dom.Submit.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Browser.Dom.CardCardCascadeNarrower'.", repo.Browser.Dom.CardCardCascadeNarrowerInfo, new RecordItemIndex(7));
            Validate.Exists(repo.Browser.Dom.CardCardCascadeNarrowerInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
