///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WakeApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("07973f8e-4ca6-4d9b-8b01-65abed1cf9f9", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WakeAppRepository repository.
        /// </summary>
        public static WakeAppRepository repo = WakeAppRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.projektbudzik.pl/Contact' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://www.projektbudzik.pl/Contact", "Chrome", "", false, false, false, true, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(1));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeWakeApp.Submit' at 46;22.", repo.WelcomeWakeApp.SubmitInfo, new RecordItemIndex(2));
            repo.WelcomeWakeApp.Submit.Click("46;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='The Name field is required.') on item 'WelcomeWakeApp.DivTagRow.TheNameFieldIsRequired'.", repo.WelcomeWakeApp.DivTagRow.TheNameFieldIsRequiredInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.WelcomeWakeApp.DivTagRow.TheNameFieldIsRequiredInfo, "InnerText", "The Name field is required.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='The Email field is required.') on item 'WelcomeWakeApp.DivTagRow.TheEmailFieldIsRequired'.", repo.WelcomeWakeApp.DivTagRow.TheEmailFieldIsRequiredInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.WelcomeWakeApp.DivTagRow.TheEmailFieldIsRequiredInfo, "InnerText", "The Email field is required.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='The Subject field is required.') on item 'WelcomeWakeApp.DivTagRow.TheSubjectFieldIsRequired'.", repo.WelcomeWakeApp.DivTagRow.TheSubjectFieldIsRequiredInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.WelcomeWakeApp.DivTagRow.TheSubjectFieldIsRequiredInfo, "InnerText", "The Subject field is required.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='The Subject field is required.') on item 'WelcomeWakeApp.DivTagRow.TheSubjectFieldIsRequired'.", repo.WelcomeWakeApp.DivTagRow.TheSubjectFieldIsRequiredInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.WelcomeWakeApp.DivTagRow.TheSubjectFieldIsRequiredInfo, "InnerText", "The Subject field is required.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (SafeClass='field-validation-error text-danger') on item 'WelcomeWakeApp.DivTagRow.TheMessageFieldIsRequired'.", repo.WelcomeWakeApp.DivTagRow.TheMessageFieldIsRequiredInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.WelcomeWakeApp.DivTagRow.TheMessageFieldIsRequiredInfo, "SafeClass", "field-validation-error text-danger");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Application", "Killing application containing item 'WelcomeWakeApp'.", repo.WelcomeWakeApp.SelfInfo, new RecordItemIndex(8));
            Host.Current.KillApplication(repo.WelcomeWakeApp.Self);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
