///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WakeApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WakeAppRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b82432a2-0496-4b32-8d7c-b7b3a367b0c3")]
    public partial class WakeAppRepository : RepoGenBaseFolder
    {
        static WakeAppRepository instance = new WakeAppRepository();
        WakeAppRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        WakeAppRepositoryFolders.WelcomeWakeAppAppFolder _welcomewakeapp;

        /// <summary>
        /// Gets the singleton class instance representing the WakeAppRepository element repository.
        /// </summary>
        [RepositoryFolder("b82432a2-0496-4b32-8d7c-b7b3a367b0c3")]
        public static WakeAppRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WakeAppRepository() 
            : base("WakeAppRepository", "/", null, 0, false, "b82432a2-0496-4b32-8d7c-b7b3a367b0c3", ".\\RepositoryImages\\WakeAppRepositoryb82432a2.rximgres")
        {
            _applicationundertest = new WakeAppRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _welcomewakeapp = new WakeAppRepositoryFolders.WelcomeWakeAppAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b82432a2-0496-4b32-8d7c-b7b3a367b0c3")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("e34f58c7-60a1-42ca-ad46-7a96f04c40df")]
        public virtual WakeAppRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The WelcomeWakeApp folder.
        /// </summary>
        [RepositoryFolder("af579ae3-af4b-4a5d-a072-16f9d944ff0f")]
        public virtual WakeAppRepositoryFolders.WelcomeWakeAppAppFolder WelcomeWakeApp
        {
            get { return _welcomewakeapp; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class WakeAppRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("e34f58c7-60a1-42ca-ad46-7a96f04c40df")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='projektbudzik.pl']", parentFolder, 30000, null, false, "e34f58c7-60a1-42ca-ad46-7a96f04c40df", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e34f58c7-60a1-42ca-ad46-7a96f04c40df")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e34f58c7-60a1-42ca-ad46-7a96f04c40df")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The WelcomeWakeAppAppFolder folder.
        /// </summary>
        [RepositoryFolder("af579ae3-af4b-4a5d-a072-16f9d944ff0f")]
        public partial class WelcomeWakeAppAppFolder : RepoGenBaseFolder
        {
            WakeAppRepositoryFolders.DFlexJustifyContentCenterMb1Pt4Folder _dflexjustifycontentcentermb1pt4;
            WakeAppRepositoryFolders.DivTagRowFolder _divtagrow;
            RepoItemInfo _httpwwwprojektbudzikplnavbaronlyInfo;
            FaFaAndroidInfoClass _fafaandroidInfo;
            RepoItemInfo _witamyInfo;
            RepoItemInfo _headsetmicInfo;
            RepoItemInfo _projektbudzikplInfo;
            RepoItemInfo _wakeappInfo;
            RepoItemInfo _divtagcwakeappprojeInfo;
            RepoItemInfo _buttontagInfo;
            RepoItemInfo _buttontag1Info;
            RepoItemInfo _fafausercircleoInfo;
            RepoItemInfo _fafaandroid1Info;
            RepoItemInfo _h5tagpobierzaplikacjęInfo;
            RepoItemInfo _kontaktInfo;
            RepoItemInfo _somedivtagInfo;
            RepoItemInfo _submitInfo;

            /// <summary>
            /// Creates a new WelcomeWakeApp  folder.
            /// </summary>
            public WelcomeWakeAppAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WelcomeWakeApp", "/dom[@domain='www.projektbudzik.pl']", parentFolder, 30000, null, false, "af579ae3-af4b-4a5d-a072-16f9d944ff0f", "")
            {
                _dflexjustifycontentcentermb1pt4 = new WakeAppRepositoryFolders.DFlexJustifyContentCenterMb1Pt4Folder(this);
                _divtagrow = new WakeAppRepositoryFolders.DivTagRowFolder(this);
                _httpwwwprojektbudzikplnavbaronlyInfo = new RepoItemInfo(this, "HttpWwwProjektbudzikPlNavbarOnly", ".//nav/?/?/a[@innertext>'                    WakeApp']/img[@alt='']", 30000, null, "3b049cb8-0153-477d-a848-4122549151f9");
                _fafaandroidInfo = new FaFaAndroidInfoClass(this);
                _witamyInfo = new RepoItemInfo(this, "Witamy", "body/div[1]/main/div/div/h1[@innertext='Witamy']", 30000, null, "64c3622d-950b-40ba-89bc-b866917b2834");
                _headsetmicInfo = new RepoItemInfo(this, "HeadsetMic", ".//nav//ul/li[2]/form[@action='http://www.projektbudzik.pl/']/button[@title='Kontakt']/i[@innertext='headset_mic']", 30000, null, "c70e6848-4462-438d-8bf6-40bfe73a2977");
                _projektbudzikplInfo = new RepoItemInfo(this, "ProjektbudzikPl", "?/?/header/nav/?/?/a[@innertext>'                    WakeApp']", 30000, null, "72227eb6-18fb-4f50-a965-89817f713b24");
                _wakeappInfo = new RepoItemInfo(this, "WakeApp", "body/div[1]/main/div/div/img[@alt='WakeApp']", 30000, null, "9f9cac08-74cf-47b5-bc52-37b957afa40d");
                _divtagcwakeappprojeInfo = new RepoItemInfo(this, "DivTagCWakeAppProje", "?/?/footer/?/?/div[@innertext>'                © WakeApp']", 30000, null, "edb369dd-323a-4fcc-81f1-e82abdca6af6");
                _buttontagInfo = new RepoItemInfo(this, "ButtonTag", "?/?/header/nav//ul/li[3]/form[@action='http://www.projektbudzik.pl/']/button[@innertext>'']", 30000, null, "7b96ee0f-f573-4d4d-a8b2-f2db086685a3");
                _buttontag1Info = new RepoItemInfo(this, "ButtonTag1", "?/?/header/nav//ul/li[4]/form[@action='http://www.projektbudzik.pl/']/button[@innertext>'']", 30000, null, "5de7e16f-d67c-469f-ba19-a298b0b27c1d");
                _fafausercircleoInfo = new RepoItemInfo(this, "FaFaUserCircleO", ".//nav//ul/li[3]/form[@action='http://www.projektbudzik.pl/']/button[@innertext>'']/i", 30000, null, "9d5869c6-76d5-4974-9973-2b09e5d7547b");
                _fafaandroid1Info = new RepoItemInfo(this, "FaFaAndroid1", "body/div//h5[@innertext>'                pobierz aplikację']/a[@title>'Pobierz aplikację na Andr']/i", 30000, null, "c4907e55-f8de-40d9-910f-353dec8e07a2");
                _h5tagpobierzaplikacjęInfo = new RepoItemInfo(this, "H5TagPobierzAplikację", "body/div//h5[@innertext>'                pobierz aplikację']", 30000, null, "3e1bebd1-93b0-49f5-8369-09d387ff2cf1");
                _kontaktInfo = new RepoItemInfo(this, "Kontakt", "body/div/?/?/section/h2[@innertext='Kontakt']", 30000, null, "fe7d7127-81b5-47d7-ad62-142ee7f626c6");
                _somedivtagInfo = new RepoItemInfo(this, "SomeDivTag", ".//div[#'map-container-section']/iframe[@src='https://maps.google.com/maps?q=Polsko-Japo%C5%84ska+Akademia+Technik+Komputerowych&t=&z=15&ie=UTF8&iwloc=&output=embed']//div[#'mapDiv']/div/div/div[1]/div[3]", 30000, null, "f6846fb0-6c32-4292-91d8-b916cca10a63");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//button[#'submit']", 30000, null, "a7b3baed-49f6-43be-9ecb-75c46a8de6b5");
            }

            /// <summary>
            /// The FaFaAndroidInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("52ff9d1b-1500-4d2d-853b-677b120e429c")]
            public class FaFaAndroidInfoClass : RepoItemInfo
            {
                /// <summary>
                /// FaFaAndroidInfoClass class constructor.
                /// </summary>
                public FaFaAndroidInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "FaFaAndroid", ".//nav//ul/?/?/form[@action='http://www.projektbudzik.pl/']/a[@title>'Pobierz aplikację na Andr']/i", 30000, null, "52ff9d1b-1500-4d2d-853b-677b120e429c")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("6d7e701c-7ddc-4e4f-b5cd-38108f100140")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("6d7e701c-7ddc-4e4f-b5cd-38108f100140");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("6d7e701c-7ddc-4e4f-b5cd-38108f100140")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("6d7e701c-7ddc-4e4f-b5cd-38108f100140", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("af579ae3-af4b-4a5d-a072-16f9d944ff0f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("af579ae3-af4b-4a5d-a072-16f9d944ff0f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HttpWwwProjektbudzikPlNavbarOnly item.
            /// </summary>
            [RepositoryItem("3b049cb8-0153-477d-a848-4122549151f9")]
            public virtual Ranorex.ImgTag HttpWwwProjektbudzikPlNavbarOnly
            {
                get
                {
                    return _httpwwwprojektbudzikplnavbaronlyInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpWwwProjektbudzikPlNavbarOnly item info.
            /// </summary>
            [RepositoryItemInfo("3b049cb8-0153-477d-a848-4122549151f9")]
            public virtual RepoItemInfo HttpWwwProjektbudzikPlNavbarOnlyInfo
            {
                get
                {
                    return _httpwwwprojektbudzikplnavbaronlyInfo;
                }
            }

            /// <summary>
            /// The FaFaAndroid item.
            /// </summary>
            [RepositoryItem("52ff9d1b-1500-4d2d-853b-677b120e429c")]
            public virtual Ranorex.ITag FaFaAndroid
            {
                get
                {
                    return _fafaandroidInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FaFaAndroid item info.
            /// </summary>
            [RepositoryItemInfo("52ff9d1b-1500-4d2d-853b-677b120e429c")]
            public virtual FaFaAndroidInfoClass FaFaAndroidInfo
            {
                get
                {
                    return _fafaandroidInfo;
                }
            }

            /// <summary>
            /// The Witamy item.
            /// </summary>
            [RepositoryItem("64c3622d-950b-40ba-89bc-b866917b2834")]
            public virtual Ranorex.H1Tag Witamy
            {
                get
                {
                    return _witamyInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The Witamy item info.
            /// </summary>
            [RepositoryItemInfo("64c3622d-950b-40ba-89bc-b866917b2834")]
            public virtual RepoItemInfo WitamyInfo
            {
                get
                {
                    return _witamyInfo;
                }
            }

            /// <summary>
            /// The HeadsetMic item.
            /// </summary>
            [RepositoryItem("c70e6848-4462-438d-8bf6-40bfe73a2977")]
            public virtual Ranorex.ITag HeadsetMic
            {
                get
                {
                    return _headsetmicInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The HeadsetMic item info.
            /// </summary>
            [RepositoryItemInfo("c70e6848-4462-438d-8bf6-40bfe73a2977")]
            public virtual RepoItemInfo HeadsetMicInfo
            {
                get
                {
                    return _headsetmicInfo;
                }
            }

            /// <summary>
            /// The ProjektbudzikPl item.
            /// </summary>
            [RepositoryItem("72227eb6-18fb-4f50-a965-89817f713b24")]
            public virtual Ranorex.ATag ProjektbudzikPl
            {
                get
                {
                    return _projektbudzikplInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ProjektbudzikPl item info.
            /// </summary>
            [RepositoryItemInfo("72227eb6-18fb-4f50-a965-89817f713b24")]
            public virtual RepoItemInfo ProjektbudzikPlInfo
            {
                get
                {
                    return _projektbudzikplInfo;
                }
            }

            /// <summary>
            /// The WakeApp item.
            /// </summary>
            [RepositoryItem("9f9cac08-74cf-47b5-bc52-37b957afa40d")]
            public virtual Ranorex.ImgTag WakeApp
            {
                get
                {
                    return _wakeappInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The WakeApp item info.
            /// </summary>
            [RepositoryItemInfo("9f9cac08-74cf-47b5-bc52-37b957afa40d")]
            public virtual RepoItemInfo WakeAppInfo
            {
                get
                {
                    return _wakeappInfo;
                }
            }

            /// <summary>
            /// The DivTagCWakeAppProje item.
            /// </summary>
            [RepositoryItem("edb369dd-323a-4fcc-81f1-e82abdca6af6")]
            public virtual Ranorex.DivTag DivTagCWakeAppProje
            {
                get
                {
                    return _divtagcwakeappprojeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagCWakeAppProje item info.
            /// </summary>
            [RepositoryItemInfo("edb369dd-323a-4fcc-81f1-e82abdca6af6")]
            public virtual RepoItemInfo DivTagCWakeAppProjeInfo
            {
                get
                {
                    return _divtagcwakeappprojeInfo;
                }
            }

            /// <summary>
            /// The ButtonTag item.
            /// </summary>
            [RepositoryItem("7b96ee0f-f573-4d4d-a8b2-f2db086685a3")]
            public virtual Ranorex.ButtonTag ButtonTag
            {
                get
                {
                    return _buttontagInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTag item info.
            /// </summary>
            [RepositoryItemInfo("7b96ee0f-f573-4d4d-a8b2-f2db086685a3")]
            public virtual RepoItemInfo ButtonTagInfo
            {
                get
                {
                    return _buttontagInfo;
                }
            }

            /// <summary>
            /// The ButtonTag1 item.
            /// </summary>
            [RepositoryItem("5de7e16f-d67c-469f-ba19-a298b0b27c1d")]
            public virtual Ranorex.ButtonTag ButtonTag1
            {
                get
                {
                    return _buttontag1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTag1 item info.
            /// </summary>
            [RepositoryItemInfo("5de7e16f-d67c-469f-ba19-a298b0b27c1d")]
            public virtual RepoItemInfo ButtonTag1Info
            {
                get
                {
                    return _buttontag1Info;
                }
            }

            /// <summary>
            /// The FaFaUserCircleO item.
            /// </summary>
            [RepositoryItem("9d5869c6-76d5-4974-9973-2b09e5d7547b")]
            public virtual Ranorex.ITag FaFaUserCircleO
            {
                get
                {
                    return _fafausercircleoInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FaFaUserCircleO item info.
            /// </summary>
            [RepositoryItemInfo("9d5869c6-76d5-4974-9973-2b09e5d7547b")]
            public virtual RepoItemInfo FaFaUserCircleOInfo
            {
                get
                {
                    return _fafausercircleoInfo;
                }
            }

            /// <summary>
            /// The FaFaAndroid1 item.
            /// </summary>
            [RepositoryItem("c4907e55-f8de-40d9-910f-353dec8e07a2")]
            public virtual Ranorex.ITag FaFaAndroid1
            {
                get
                {
                    return _fafaandroid1Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FaFaAndroid1 item info.
            /// </summary>
            [RepositoryItemInfo("c4907e55-f8de-40d9-910f-353dec8e07a2")]
            public virtual RepoItemInfo FaFaAndroid1Info
            {
                get
                {
                    return _fafaandroid1Info;
                }
            }

            /// <summary>
            /// The H5TagPobierzAplikację item.
            /// </summary>
            [RepositoryItem("3e1bebd1-93b0-49f5-8369-09d387ff2cf1")]
            public virtual Ranorex.H5Tag H5TagPobierzAplikację
            {
                get
                {
                    return _h5tagpobierzaplikacjęInfo.CreateAdapter<Ranorex.H5Tag>(true);
                }
            }

            /// <summary>
            /// The H5TagPobierzAplikację item info.
            /// </summary>
            [RepositoryItemInfo("3e1bebd1-93b0-49f5-8369-09d387ff2cf1")]
            public virtual RepoItemInfo H5TagPobierzAplikacjęInfo
            {
                get
                {
                    return _h5tagpobierzaplikacjęInfo;
                }
            }

            /// <summary>
            /// The Kontakt item.
            /// </summary>
            [RepositoryItem("fe7d7127-81b5-47d7-ad62-142ee7f626c6")]
            public virtual Ranorex.H2Tag Kontakt
            {
                get
                {
                    return _kontaktInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The Kontakt item info.
            /// </summary>
            [RepositoryItemInfo("fe7d7127-81b5-47d7-ad62-142ee7f626c6")]
            public virtual RepoItemInfo KontaktInfo
            {
                get
                {
                    return _kontaktInfo;
                }
            }

            /// <summary>
            /// The SomeDivTag item.
            /// </summary>
            [RepositoryItem("f6846fb0-6c32-4292-91d8-b916cca10a63")]
            public virtual Ranorex.DivTag SomeDivTag
            {
                get
                {
                    return _somedivtagInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SomeDivTag item info.
            /// </summary>
            [RepositoryItemInfo("f6846fb0-6c32-4292-91d8-b916cca10a63")]
            public virtual RepoItemInfo SomeDivTagInfo
            {
                get
                {
                    return _somedivtagInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("a7b3baed-49f6-43be-9ecb-75c46a8de6b5")]
            public virtual Ranorex.ButtonTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("a7b3baed-49f6-43be-9ecb-75c46a8de6b5")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The DFlexJustifyContentCenterMb1Pt4 folder.
            /// </summary>
            [RepositoryFolder("b3a1e41c-84bc-4c7f-a4b6-21cf5344c79f")]
            public virtual WakeAppRepositoryFolders.DFlexJustifyContentCenterMb1Pt4Folder DFlexJustifyContentCenterMb1Pt4
            {
                get { return _dflexjustifycontentcentermb1pt4; }
            }

            /// <summary>
            /// The DivTagRow folder.
            /// </summary>
            [RepositoryFolder("5ddda5fd-8020-4a92-8a1d-7ca34811d11e")]
            public virtual WakeAppRepositoryFolders.DivTagRowFolder DivTagRow
            {
                get { return _divtagrow; }
            }
        }

        /// <summary>
        /// The DFlexJustifyContentCenterMb1Pt4Folder folder.
        /// </summary>
        [RepositoryFolder("b3a1e41c-84bc-4c7f-a4b6-21cf5344c79f")]
        public partial class DFlexJustifyContentCenterMb1Pt4Folder : RepoGenBaseFolder
        {
            RepoItemInfo _onasInfo;
            RepoItemInfo _politykaprywatnościInfo;
            RepoItemInfo _pomocInfo;
            RepoItemInfo _kontaktInfo;
            RepoItemInfo _fafagithubInfo;
            RepoItemInfo _httpwwwprojektbudzikpllogorndpngInfo;

            /// <summary>
            /// Creates a new DFlexJustifyContentCenterMb1Pt4  folder.
            /// </summary>
            public DFlexJustifyContentCenterMb1Pt4Folder(RepoGenBaseFolder parentFolder) :
                    base("DFlexJustifyContentCenterMb1Pt4", "?/?/footer/div/div[1]", parentFolder, 30000, null, false, "b3a1e41c-84bc-4c7f-a4b6-21cf5344c79f", "")
            {
                _onasInfo = new RepoItemInfo(this, "ONas", "div[1]/?/?/a[@innertext='O nas']", 30000, null, "2521d8fd-9d88-4c20-bbbe-4ef5a5ee858c");
                _politykaprywatnościInfo = new RepoItemInfo(this, "PolitykaPrywatności", "div[2]/?/?/a[@innertext='Polityka prywatności']", 30000, null, "f0e87bd2-38fd-4045-b6d4-47b58693ec1d");
                _pomocInfo = new RepoItemInfo(this, "Pomoc", "div[3]/?/?/a[@innertext='Pomoc']", 30000, null, "4397a601-4213-4857-a59f-a4e1ed4c25ab");
                _kontaktInfo = new RepoItemInfo(this, "Kontakt", "div[4]/?/?/a[@innertext='Kontakt']", 30000, null, "d83984be-0dd2-4bc7-8c90-fba6984e5f6b");
                _fafagithubInfo = new RepoItemInfo(this, "FaFaGithub", "div[5]/?/?/a[@title='github.com']/i", 30000, null, "f9413d29-204d-4f78-992d-5bd761648b9a");
                _httpwwwprojektbudzikpllogorndpngInfo = new RepoItemInfo(this, "HttpWwwProjektbudzikPlLogoRndPng", "img[@src='http://www.projektbudzik.pl/logo-rnd.png']", 30000, null, "c15765e7-4354-4f2c-bfac-43e6a9d11522");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b3a1e41c-84bc-4c7f-a4b6-21cf5344c79f")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b3a1e41c-84bc-4c7f-a4b6-21cf5344c79f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ONas item.
            /// </summary>
            [RepositoryItem("2521d8fd-9d88-4c20-bbbe-4ef5a5ee858c")]
            public virtual Ranorex.ATag ONas
            {
                get
                {
                    return _onasInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ONas item info.
            /// </summary>
            [RepositoryItemInfo("2521d8fd-9d88-4c20-bbbe-4ef5a5ee858c")]
            public virtual RepoItemInfo ONasInfo
            {
                get
                {
                    return _onasInfo;
                }
            }

            /// <summary>
            /// The PolitykaPrywatności item.
            /// </summary>
            [RepositoryItem("f0e87bd2-38fd-4045-b6d4-47b58693ec1d")]
            public virtual Ranorex.ATag PolitykaPrywatności
            {
                get
                {
                    return _politykaprywatnościInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The PolitykaPrywatności item info.
            /// </summary>
            [RepositoryItemInfo("f0e87bd2-38fd-4045-b6d4-47b58693ec1d")]
            public virtual RepoItemInfo PolitykaPrywatnościInfo
            {
                get
                {
                    return _politykaprywatnościInfo;
                }
            }

            /// <summary>
            /// The Pomoc item.
            /// </summary>
            [RepositoryItem("4397a601-4213-4857-a59f-a4e1ed4c25ab")]
            public virtual Ranorex.ATag Pomoc
            {
                get
                {
                    return _pomocInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Pomoc item info.
            /// </summary>
            [RepositoryItemInfo("4397a601-4213-4857-a59f-a4e1ed4c25ab")]
            public virtual RepoItemInfo PomocInfo
            {
                get
                {
                    return _pomocInfo;
                }
            }

            /// <summary>
            /// The Kontakt item.
            /// </summary>
            [RepositoryItem("d83984be-0dd2-4bc7-8c90-fba6984e5f6b")]
            public virtual Ranorex.ATag Kontakt
            {
                get
                {
                    return _kontaktInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Kontakt item info.
            /// </summary>
            [RepositoryItemInfo("d83984be-0dd2-4bc7-8c90-fba6984e5f6b")]
            public virtual RepoItemInfo KontaktInfo
            {
                get
                {
                    return _kontaktInfo;
                }
            }

            /// <summary>
            /// The FaFaGithub item.
            /// </summary>
            [RepositoryItem("f9413d29-204d-4f78-992d-5bd761648b9a")]
            public virtual Ranorex.ITag FaFaGithub
            {
                get
                {
                    return _fafagithubInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FaFaGithub item info.
            /// </summary>
            [RepositoryItemInfo("f9413d29-204d-4f78-992d-5bd761648b9a")]
            public virtual RepoItemInfo FaFaGithubInfo
            {
                get
                {
                    return _fafagithubInfo;
                }
            }

            /// <summary>
            /// The HttpWwwProjektbudzikPlLogoRndPng item.
            /// </summary>
            [RepositoryItem("c15765e7-4354-4f2c-bfac-43e6a9d11522")]
            public virtual Ranorex.ImgTag HttpWwwProjektbudzikPlLogoRndPng
            {
                get
                {
                    return _httpwwwprojektbudzikpllogorndpngInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpWwwProjektbudzikPlLogoRndPng item info.
            /// </summary>
            [RepositoryItemInfo("c15765e7-4354-4f2c-bfac-43e6a9d11522")]
            public virtual RepoItemInfo HttpWwwProjektbudzikPlLogoRndPngInfo
            {
                get
                {
                    return _httpwwwprojektbudzikpllogorndpngInfo;
                }
            }
        }

        /// <summary>
        /// The DivTagRowFolder folder.
        /// </summary>
        [RepositoryFolder("5ddda5fd-8020-4a92-8a1d-7ca34811d11e")]
        public partial class DivTagRowFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fafawrenchInfo;
            RepoItemInfo _h3tagwyślijnamwiadomośćInfo;
            RepoItemInfo _fafamapmarkerInfo;
            RepoItemInfo _thenamefieldisrequiredInfo;
            RepoItemInfo _theemailfieldisrequiredInfo;
            RepoItemInfo _thesubjectfieldisrequiredInfo;
            RepoItemInfo _themessagefieldisrequiredInfo;

            /// <summary>
            /// Creates a new DivTagRow  folder.
            /// </summary>
            public DivTagRowFolder(RepoGenBaseFolder parentFolder) :
                    base("DivTagRow", "body/div/?/?/section/div[1]", parentFolder, 30000, null, false, "5ddda5fd-8020-4a92-8a1d-7ca34811d11e", "")
            {
                _fafawrenchInfo = new RepoItemInfo(this, "FaFaWrench", ".//a/i", 30000, null, "f23360cc-45aa-4d36-b245-8d957e0592cb");
                _h3tagwyślijnamwiadomośćInfo = new RepoItemInfo(this, "H3TagWyślijNamWiadomość", "div[1]/div/div/div/h3[@innertext=' Wyślij nam wiadomość']", 30000, null, "a68f6978-d2c7-4469-881c-76b9caa52b6a");
                _fafamapmarkerInfo = new RepoItemInfo(this, "FaFaMapMarker", "div[2]/div[2]/div[1]/i", 30000, null, "95462c65-6b8a-4bc3-a8ec-d65f59aa9d9e");
                _thenamefieldisrequiredInfo = new RepoItemInfo(this, "TheNameFieldIsRequired", ".//form[@action='http://www.projektbudzik.pl/Contact']/div[1]/span[@innertext>'The Name field is require']", 30000, null, "78bb5c62-1ab9-40b8-864a-977820db931f");
                _theemailfieldisrequiredInfo = new RepoItemInfo(this, "TheEmailFieldIsRequired", ".//form[@action='http://www.projektbudzik.pl/Contact']/div[2]/span[@innertext>'The Email field is requir']", 30000, null, "d3541a73-c2d1-49eb-847e-45994639d706");
                _thesubjectfieldisrequiredInfo = new RepoItemInfo(this, "TheSubjectFieldIsRequired", ".//form[@action='http://www.projektbudzik.pl/Contact']/div[4]/span[@innertext>'The Subject field is requ']", 30000, null, "5b691459-4b2c-4bd2-9ed7-3d8339fe11c5");
                _themessagefieldisrequiredInfo = new RepoItemInfo(this, "TheMessageFieldIsRequired", ".//form[@action='http://www.projektbudzik.pl/Contact']/div[5]/span[@innertext>'The Message field is requ']", 30000, null, "1148da5f-26de-47cc-892e-442616c75127");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5ddda5fd-8020-4a92-8a1d-7ca34811d11e")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5ddda5fd-8020-4a92-8a1d-7ca34811d11e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FaFaWrench item.
            /// </summary>
            [RepositoryItem("f23360cc-45aa-4d36-b245-8d957e0592cb")]
            public virtual Ranorex.ITag FaFaWrench
            {
                get
                {
                    return _fafawrenchInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FaFaWrench item info.
            /// </summary>
            [RepositoryItemInfo("f23360cc-45aa-4d36-b245-8d957e0592cb")]
            public virtual RepoItemInfo FaFaWrenchInfo
            {
                get
                {
                    return _fafawrenchInfo;
                }
            }

            /// <summary>
            /// The H3TagWyślijNamWiadomość item.
            /// </summary>
            [RepositoryItem("a68f6978-d2c7-4469-881c-76b9caa52b6a")]
            public virtual Ranorex.H3Tag H3TagWyślijNamWiadomość
            {
                get
                {
                    return _h3tagwyślijnamwiadomośćInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The H3TagWyślijNamWiadomość item info.
            /// </summary>
            [RepositoryItemInfo("a68f6978-d2c7-4469-881c-76b9caa52b6a")]
            public virtual RepoItemInfo H3TagWyślijNamWiadomośćInfo
            {
                get
                {
                    return _h3tagwyślijnamwiadomośćInfo;
                }
            }

            /// <summary>
            /// The FaFaMapMarker item.
            /// </summary>
            [RepositoryItem("95462c65-6b8a-4bc3-a8ec-d65f59aa9d9e")]
            public virtual Ranorex.ITag FaFaMapMarker
            {
                get
                {
                    return _fafamapmarkerInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FaFaMapMarker item info.
            /// </summary>
            [RepositoryItemInfo("95462c65-6b8a-4bc3-a8ec-d65f59aa9d9e")]
            public virtual RepoItemInfo FaFaMapMarkerInfo
            {
                get
                {
                    return _fafamapmarkerInfo;
                }
            }

            /// <summary>
            /// The TheNameFieldIsRequired item.
            /// </summary>
            [RepositoryItem("78bb5c62-1ab9-40b8-864a-977820db931f")]
            public virtual Ranorex.SpanTag TheNameFieldIsRequired
            {
                get
                {
                    return _thenamefieldisrequiredInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TheNameFieldIsRequired item info.
            /// </summary>
            [RepositoryItemInfo("78bb5c62-1ab9-40b8-864a-977820db931f")]
            public virtual RepoItemInfo TheNameFieldIsRequiredInfo
            {
                get
                {
                    return _thenamefieldisrequiredInfo;
                }
            }

            /// <summary>
            /// The TheEmailFieldIsRequired item.
            /// </summary>
            [RepositoryItem("d3541a73-c2d1-49eb-847e-45994639d706")]
            public virtual Ranorex.SpanTag TheEmailFieldIsRequired
            {
                get
                {
                    return _theemailfieldisrequiredInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TheEmailFieldIsRequired item info.
            /// </summary>
            [RepositoryItemInfo("d3541a73-c2d1-49eb-847e-45994639d706")]
            public virtual RepoItemInfo TheEmailFieldIsRequiredInfo
            {
                get
                {
                    return _theemailfieldisrequiredInfo;
                }
            }

            /// <summary>
            /// The TheSubjectFieldIsRequired item.
            /// </summary>
            [RepositoryItem("5b691459-4b2c-4bd2-9ed7-3d8339fe11c5")]
            public virtual Ranorex.SpanTag TheSubjectFieldIsRequired
            {
                get
                {
                    return _thesubjectfieldisrequiredInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TheSubjectFieldIsRequired item info.
            /// </summary>
            [RepositoryItemInfo("5b691459-4b2c-4bd2-9ed7-3d8339fe11c5")]
            public virtual RepoItemInfo TheSubjectFieldIsRequiredInfo
            {
                get
                {
                    return _thesubjectfieldisrequiredInfo;
                }
            }

            /// <summary>
            /// The TheMessageFieldIsRequired item.
            /// </summary>
            [RepositoryItem("1148da5f-26de-47cc-892e-442616c75127")]
            public virtual Ranorex.SpanTag TheMessageFieldIsRequired
            {
                get
                {
                    return _themessagefieldisrequiredInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TheMessageFieldIsRequired item info.
            /// </summary>
            [RepositoryItemInfo("1148da5f-26de-47cc-892e-442616c75127")]
            public virtual RepoItemInfo TheMessageFieldIsRequiredInfo
            {
                get
                {
                    return _themessagefieldisrequiredInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
