///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WakeApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WakeAppRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b82432a2-0496-4b32-8d7c-b7b3a367b0c3")]
    public partial class WakeAppRepository : RepoGenBaseFolder
    {
        static WakeAppRepository instance = new WakeAppRepository();
        WakeAppRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        WakeAppRepositoryFolders.WelcomeWakeAppAppFolder _welcomewakeapp;
        WakeAppRepositoryFolders.BrowserAppFolder _browser;
        WakeAppRepositoryFolders.DropdownAppFolder _dropdown;

        /// <summary>
        /// Gets the singleton class instance representing the WakeAppRepository element repository.
        /// </summary>
        [RepositoryFolder("b82432a2-0496-4b32-8d7c-b7b3a367b0c3")]
        public static WakeAppRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WakeAppRepository() 
            : base("WakeAppRepository", "/", null, 0, false, "b82432a2-0496-4b32-8d7c-b7b3a367b0c3", ".\\RepositoryImages\\WakeAppRepositoryb82432a2.rximgres")
        {
            _applicationundertest = new WakeAppRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _welcomewakeapp = new WakeAppRepositoryFolders.WelcomeWakeAppAppFolder(this);
            _browser = new WakeAppRepositoryFolders.BrowserAppFolder(this);
            _dropdown = new WakeAppRepositoryFolders.DropdownAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b82432a2-0496-4b32-8d7c-b7b3a367b0c3")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("e34f58c7-60a1-42ca-ad46-7a96f04c40df")]
        public virtual WakeAppRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The WelcomeWakeApp folder.
        /// </summary>
        [RepositoryFolder("af579ae3-af4b-4a5d-a072-16f9d944ff0f")]
        public virtual WakeAppRepositoryFolders.WelcomeWakeAppAppFolder WelcomeWakeApp
        {
            get { return _welcomewakeapp; }
        }

        /// <summary>
        /// The Browser folder.
        /// </summary>
        [RepositoryFolder("7855513f-a5aa-42d6-b5ea-7ef3d15754d4")]
        public virtual WakeAppRepositoryFolders.BrowserAppFolder Browser
        {
            get { return _browser; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("bedc4ef0-6b21-4e8b-b20c-72a1e3ae491d")]
        public virtual WakeAppRepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class WakeAppRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("e34f58c7-60a1-42ca-ad46-7a96f04c40df")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='projektbudzik.pl']", parentFolder, 30000, null, false, "e34f58c7-60a1-42ca-ad46-7a96f04c40df", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e34f58c7-60a1-42ca-ad46-7a96f04c40df")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e34f58c7-60a1-42ca-ad46-7a96f04c40df")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The WelcomeWakeAppAppFolder folder.
        /// </summary>
        [RepositoryFolder("af579ae3-af4b-4a5d-a072-16f9d944ff0f")]
        public partial class WelcomeWakeAppAppFolder : RepoGenBaseFolder
        {
            WakeAppRepositoryFolders.DFlexJustifyContentCenterMb1Pt4Folder _dflexjustifycontentcentermb1pt4;
            WakeAppRepositoryFolders.DivTagRowFolder _divtagrow;
            RepoItemInfo _projektbudzikplInfo;
            RepoItemInfo _wakeappInfo;
            RepoItemInfo _divtagcwakeappprojeInfo;
            RepoItemInfo _pobierzaplikacjęnaandroidaInfo;
            RepoItemInfo _kontakt1Info;
            RepoItemInfo _tastronawykorzystujeplikicookieInfo;
            RepoItemInfo _navitemInfo;
            RepoItemInfo _zamknijInfo;
            RepoItemInfo _submit1Info;
            RepoItemInfo _nameerrorInfo;
            RepoItemInfo _emailerrorInfo;
            RepoItemInfo _passworderrorInfo;
            RepoItemInfo _confirmpassworderrorInfo;
            RepoItemInfo _groupnameerrorInfo;
            RepoItemInfo _grouppassworderrorInfo;
            RepoItemInfo _nameInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _confirmpasswordInfo;
            RepoItemInfo _groupnameInfo;
            RepoItemInfo _grouppasswordInfo;
            RepoItemInfo _groupconfirmpasswordInfo;
            RepoItemInfo _subjecterrorInfo;
            RepoItemInfo _messageerrorInfo;
            RepoItemInfo _phoneInfo;
            RepoItemInfo _subjectInfo;
            RepoItemInfo _messageInfo;
            RepoItemInfo _dziękujemyzakontaktodpiszemynajszybInfo;
            RepoItemInfo _createnewgroupInfo;
            RepoItemInfo _divtagcolInfo;
            RepoItemInfo _divtagcol1Info;
            RepoItemInfo _buttontagInfo;
            RepoItemInfo _buttontag1Info;
            RepoItemInfo _inputtagmacInfo;
            RepoItemInfo _commentInfo;
            RepoItemInfo _mondayInfo;
            RepoItemInfo _dateendInfo;
            RepoItemInfo _datestartInfo;
            RepoItemInfo _repeatInfo;
            RepoItemInfo _wednesdayInfo;
            RepoItemInfo _buttontag2Info;
            RepoItemInfo _devicesotherInfo;
            RepoItemInfo _someatagInfo;
            RepoItemInfo _devicesother1Info;
            RepoItemInfo _fafaplusInfo;
            RepoItemInfo _devicetypeInfo;
            RepoItemInfo _deviceidInfo;
            RepoItemInfo _fafaplus1Info;
            RepoItemInfo _fridayInfo;
            RepoItemInfo _tuesdayInfo;
            RepoItemInfo _devicesother2Info;

            /// <summary>
            /// Creates a new WelcomeWakeApp  folder.
            /// </summary>
            public WelcomeWakeAppAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WelcomeWakeApp", "/dom[@domain='www.projektbudzik.pl']", parentFolder, 30000, null, false, "af579ae3-af4b-4a5d-a072-16f9d944ff0f", "")
            {
                _dflexjustifycontentcentermb1pt4 = new WakeAppRepositoryFolders.DFlexJustifyContentCenterMb1Pt4Folder(this);
                _divtagrow = new WakeAppRepositoryFolders.DivTagRowFolder(this);
                _projektbudzikplInfo = new RepoItemInfo(this, "ProjektbudzikPl", "?/?/header/nav/?/?/a[@innertext>'                    WakeApp']", 30000, null, "72227eb6-18fb-4f50-a965-89817f713b24");
                _wakeappInfo = new RepoItemInfo(this, "WakeApp", "body/div[1]/main/div/div/img[@alt='WakeApp']", 30000, null, "9f9cac08-74cf-47b5-bc52-37b957afa40d");
                _divtagcwakeappprojeInfo = new RepoItemInfo(this, "DivTagCWakeAppProje", "?/?/footer/?/?/div[@innertext>'                © WakeApp']", 30000, null, "edb369dd-323a-4fcc-81f1-e82abdca6af6");
                _pobierzaplikacjęnaandroidaInfo = new RepoItemInfo(this, "PobierzAplikacjęNaAndroida", "?/?/header/nav//ul/?/?/form[@action='http://www.projektbudzik.pl/']/a[@title>'Pobierz aplikację na Andr']", 30000, null, "34bac232-6509-48ac-93e0-d6593fe5dd70");
                _kontakt1Info = new RepoItemInfo(this, "Kontakt1", "?/?/header/nav//ul/li[2]/form[@action='http://www.projektbudzik.pl/']/button[@title='Kontakt']", 30000, null, "94d6584c-8239-4847-85e9-bea13d203319");
                _tastronawykorzystujeplikicookieInfo = new RepoItemInfo(this, "TaStronaWykorzystujePlikiCookie", ".//div[#'cookieinfo']/h6[@innertext>'Ta strona wykorzystuje pliki']", 30000, null, "9a37b010-3d99-4d3d-b65f-9b57b22de612");
                _navitemInfo = new RepoItemInfo(this, "NavItem", "?/?/header/nav//ul/li[4]", 30000, null, "48edf724-1806-440e-938b-77a9c66cb4c0");
                _zamknijInfo = new RepoItemInfo(this, "Zamknij", ".//div[#'cookieinfo']/a[@innertext='x']", 30000, null, "a0fae0bc-55ec-43c4-b657-43d08560d722");
                _submit1Info = new RepoItemInfo(this, "Submit1", "body/div[1]/?/?/section//form[@action='http://www.projektbudzik.pl/Account/Register']/div[5]/div[6]/input[@type='submit']", 30000, null, "2cfb75a2-96bd-4e84-bc01-26c30c425ca0");
                _nameerrorInfo = new RepoItemInfo(this, "NameError", ".//span[#'Name-error']", 30000, null, "5824f8a9-a2cc-40ea-91bd-204f3f90d7d5");
                _emailerrorInfo = new RepoItemInfo(this, "EmailError", ".//span[#'Email-error']", 30000, null, "cc74656e-cc9b-4909-b0ae-12016589e824");
                _passworderrorInfo = new RepoItemInfo(this, "PasswordError", ".//span[#'Password-error']", 30000, null, "84c91e27-6ce5-4c12-9d6a-cb68cca765f0");
                _confirmpassworderrorInfo = new RepoItemInfo(this, "ConfirmPasswordError", ".//span[#'ConfirmPassword-error']", 30000, null, "c429f0e9-6ec2-4f79-9245-785e476d088b");
                _groupnameerrorInfo = new RepoItemInfo(this, "GroupNameError", ".//span[#'GroupName-error']", 30000, null, "16c519b4-b599-4983-970c-31ef1c8c78f3");
                _grouppassworderrorInfo = new RepoItemInfo(this, "GroupPasswordError", ".//span[#'GroupPassword-error']", 30000, null, "c01d1c37-1065-4ef1-8fde-4b79b6537ac9");
                _nameInfo = new RepoItemInfo(this, "Name", ".//input[#'Name']", 30000, null, "16dffdea-8194-4848-a1fd-e0b4caff8d3b");
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'Email']", 30000, null, "555f779d-8591-46cd-98d8-7a938b4f2b25");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'Password']", 30000, null, "a0753bc4-a813-46a6-b17e-42721665eb9e");
                _confirmpasswordInfo = new RepoItemInfo(this, "ConfirmPassword", ".//input[#'ConfirmPassword']", 30000, null, "9a3d6e44-2da3-438a-85e8-febe4d1cd26f");
                _groupnameInfo = new RepoItemInfo(this, "GroupName", ".//input[#'GroupName']", 30000, null, "d836de61-74d7-4688-ac44-562f7849a78b");
                _grouppasswordInfo = new RepoItemInfo(this, "GroupPassword", ".//input[#'GroupPassword']", 30000, null, "cfc5af30-4216-4f5d-aa9f-6114342b0fb4");
                _groupconfirmpasswordInfo = new RepoItemInfo(this, "GroupConfirmPassword", ".//input[#'GroupConfirmPassword']", 30000, null, "264e39d3-92ba-479e-a754-46c255689803");
                _subjecterrorInfo = new RepoItemInfo(this, "SubjectError", ".//span[#'Subject-error']", 30000, null, "aae5de0b-36d0-449c-baf8-4be1efddb004");
                _messageerrorInfo = new RepoItemInfo(this, "MessageError", ".//span[#'Message-error']", 30000, null, "c20009e1-8a20-4c72-b518-86e9d2133cf6");
                _phoneInfo = new RepoItemInfo(this, "Phone", ".//input[#'Phone']", 30000, null, "b6157f17-0bd3-460b-a64c-0646e713a50d");
                _subjectInfo = new RepoItemInfo(this, "Subject", ".//input[#'Subject']", 30000, null, "e928cf28-20d2-4667-834e-684ce06a63b8");
                _messageInfo = new RepoItemInfo(this, "Message", ".//textarea[#'Message']", 30000, null, "bf5c6af0-9d4e-41da-9a80-fbee6c34f2f6");
                _dziękujemyzakontaktodpiszemynajszybInfo = new RepoItemInfo(this, "DziękujemyZaKontaktOdpiszemyNajszyb", "body/div[1]/?/?/section/?/?/h4[@innertext>'Dziękujemy za kontakt. Odpiszemy']", 30000, null, "cf5ea3cd-cbad-414a-9df0-e6f2d61161f3");
                _createnewgroupInfo = new RepoItemInfo(this, "CreateNewGroup", "body/div[1]/?/?/section//form[@action='http://www.projektbudzik.pl/Account/Register']/div[5]/div[2]/label[@innertext>' Utwórz nową grupę']/input[@id='CreateNewGroup']", 30000, null, "ef699eab-8a4b-4695-9377-0fa8e179ca99");
                _divtagcolInfo = new RepoItemInfo(this, "DivTagCol", "body/div[1]/main/div/div[2]/div/div[1]", 30000, null, "865b39fd-6b42-4f4b-8b53-6af627f7172e");
                _divtagcol1Info = new RepoItemInfo(this, "DivTagCol1", "body/div[1]/main/div/div[2]/div/div[2]", 30000, null, "cfa7a4cc-756a-4604-8b68-a6c793f8318d");
                _buttontagInfo = new RepoItemInfo(this, "ButtonTag", ".//input[#'Email']", 30000, null, "692dcf19-4266-43fc-b7b7-d7dc825cc5f7");
                _buttontag1Info = new RepoItemInfo(this, "ButtonTag1", "body/header/nav//ul/?/?/form[@action='http://www.projektbudzik.pl/']/?/?/i[@innertext='devices_other']", 30000, null, "3e991043-7423-4667-a8d9-9f6d1df70a8d");
                _inputtagmacInfo = new RepoItemInfo(this, "InputTagMac", ".//input[#'Mac']", 30000, null, "67bf71cd-929b-4e45-a947-8c100889c2a8");
                _commentInfo = new RepoItemInfo(this, "Comment", ".//textarea[#'Comment']", 30000, null, "f6cbe7b6-3133-408c-bdcf-ffc526678eab");
                _mondayInfo = new RepoItemInfo(this, "Monday", ".//input[#'Monday']", 30000, null, "d4e2a19e-b6fa-4beb-8fd7-6524d0d23aef");
                _dateendInfo = new RepoItemInfo(this, "DateEnd", ".//input[#'DateEnd']", 30000, null, "d5b5a516-55b2-4a10-a709-8bd84342b1eb");
                _datestartInfo = new RepoItemInfo(this, "DateStart", ".//input[#'DateStart']", 30000, null, "dd046d50-8421-4faf-962b-282474c73906");
                _repeatInfo = new RepoItemInfo(this, "Repeat", ".//input[#'Repeat']", 30000, null, "195f1e99-9582-4ef1-8001-e8ba3f0d05be");
                _wednesdayInfo = new RepoItemInfo(this, "Wednesday", ".//input[#'Wednesday']", 30000, null, "d1c7a0de-72c8-4744-8f1f-bc163b13aed1");
                _buttontag2Info = new RepoItemInfo(this, "ButtonTag2", "body/div[1]/?/?/section//a[@innertext>'                     Dodaj']", 30000, null, "161d428d-a548-44dd-bacc-a31c5ac754e7");
                _devicesotherInfo = new RepoItemInfo(this, "DevicesOther", "?/?/header/nav//ul/?/?/form[@action='http://www.projektbudzik.pl/Alarm']/?/?/i[@innertext='devices_other']", 30000, null, "ef86b687-a6df-4643-bfe1-98dc10d132a6");
                _someatagInfo = new RepoItemInfo(this, "SomeATag", "body/div[1]/?/?/section/?/?/table/tbody/tr/td[5]/?/?/a[@innertext>'' and @href=null()]", 30000, null, "5e585588-7bb8-4842-828d-8264d2ff35e3");
                _devicesother1Info = new RepoItemInfo(this, "DevicesOther1", "?/?/header/nav//ul/?/?/form[@action='http://www.projektbudzik.pl/Device?']/?/?/i[@innertext='devices_other']", 30000, null, "09f72e69-9e4e-4443-b42f-bf23afd95c06");
                _fafaplusInfo = new RepoItemInfo(this, "FaFaPlus", "body/div[1]/?/?/section//a[@innertext>'                     Dodaj']/i", 30000, null, "ba7fcd07-678e-4893-b2a0-d5ed2e89b3db");
                _devicetypeInfo = new RepoItemInfo(this, "DeviceType", ".//select[#'DeviceType']", 30000, null, "ecbb2e2f-a841-4c2a-b20a-0faa8e98deec");
                _deviceidInfo = new RepoItemInfo(this, "DeviceId", ".//select[#'DeviceId']", 30000, null, "facb4155-e1bc-491e-b22c-cfb47e598487");
                _fafaplus1Info = new RepoItemInfo(this, "FaFaPlus1", "body/div[1]/?/?/section//a[@innertext>'                Dodaj']/i", 30000, null, "bdb6bbf3-35a9-435e-af43-f6281c595c0c");
                _fridayInfo = new RepoItemInfo(this, "Friday", ".//input[#'Friday']", 30000, null, "60f9c6ad-fde5-4bda-9c60-9b181df23cb8");
                _tuesdayInfo = new RepoItemInfo(this, "Tuesday", ".//input[#'Tuesday']", 30000, null, "551f5075-cafb-4839-b2f7-4236721a5c9e");
                _devicesother2Info = new RepoItemInfo(this, "DevicesOther2", "?/?/header/nav//ul/?/?/form[@action='http://www.projektbudzik.pl/Alarm?deviceId=10068']/?/?/i[@innertext='devices_other']", 30000, null, "20b3938e-9b8d-4433-9859-1a4aff52464b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("af579ae3-af4b-4a5d-a072-16f9d944ff0f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("af579ae3-af4b-4a5d-a072-16f9d944ff0f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProjektbudzikPl item.
            /// </summary>
            [RepositoryItem("72227eb6-18fb-4f50-a965-89817f713b24")]
            public virtual Ranorex.ATag ProjektbudzikPl
            {
                get
                {
                    return _projektbudzikplInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ProjektbudzikPl item info.
            /// </summary>
            [RepositoryItemInfo("72227eb6-18fb-4f50-a965-89817f713b24")]
            public virtual RepoItemInfo ProjektbudzikPlInfo
            {
                get
                {
                    return _projektbudzikplInfo;
                }
            }

            /// <summary>
            /// The WakeApp item.
            /// </summary>
            [RepositoryItem("9f9cac08-74cf-47b5-bc52-37b957afa40d")]
            public virtual Ranorex.ImgTag WakeApp
            {
                get
                {
                    return _wakeappInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The WakeApp item info.
            /// </summary>
            [RepositoryItemInfo("9f9cac08-74cf-47b5-bc52-37b957afa40d")]
            public virtual RepoItemInfo WakeAppInfo
            {
                get
                {
                    return _wakeappInfo;
                }
            }

            /// <summary>
            /// The DivTagCWakeAppProje item.
            /// </summary>
            [RepositoryItem("edb369dd-323a-4fcc-81f1-e82abdca6af6")]
            public virtual Ranorex.DivTag DivTagCWakeAppProje
            {
                get
                {
                    return _divtagcwakeappprojeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagCWakeAppProje item info.
            /// </summary>
            [RepositoryItemInfo("edb369dd-323a-4fcc-81f1-e82abdca6af6")]
            public virtual RepoItemInfo DivTagCWakeAppProjeInfo
            {
                get
                {
                    return _divtagcwakeappprojeInfo;
                }
            }

            /// <summary>
            /// The PobierzAplikacjęNaAndroida item.
            /// </summary>
            [RepositoryItem("34bac232-6509-48ac-93e0-d6593fe5dd70")]
            public virtual Ranorex.ATag PobierzAplikacjęNaAndroida
            {
                get
                {
                    return _pobierzaplikacjęnaandroidaInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The PobierzAplikacjęNaAndroida item info.
            /// </summary>
            [RepositoryItemInfo("34bac232-6509-48ac-93e0-d6593fe5dd70")]
            public virtual RepoItemInfo PobierzAplikacjęNaAndroidaInfo
            {
                get
                {
                    return _pobierzaplikacjęnaandroidaInfo;
                }
            }

            /// <summary>
            /// The Kontakt1 item.
            /// </summary>
            [RepositoryItem("94d6584c-8239-4847-85e9-bea13d203319")]
            public virtual Ranorex.ButtonTag Kontakt1
            {
                get
                {
                    return _kontakt1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Kontakt1 item info.
            /// </summary>
            [RepositoryItemInfo("94d6584c-8239-4847-85e9-bea13d203319")]
            public virtual RepoItemInfo Kontakt1Info
            {
                get
                {
                    return _kontakt1Info;
                }
            }

            /// <summary>
            /// The TaStronaWykorzystujePlikiCookie item.
            /// </summary>
            [RepositoryItem("9a37b010-3d99-4d3d-b65f-9b57b22de612")]
            public virtual Ranorex.H6Tag TaStronaWykorzystujePlikiCookie
            {
                get
                {
                    return _tastronawykorzystujeplikicookieInfo.CreateAdapter<Ranorex.H6Tag>(true);
                }
            }

            /// <summary>
            /// The TaStronaWykorzystujePlikiCookie item info.
            /// </summary>
            [RepositoryItemInfo("9a37b010-3d99-4d3d-b65f-9b57b22de612")]
            public virtual RepoItemInfo TaStronaWykorzystujePlikiCookieInfo
            {
                get
                {
                    return _tastronawykorzystujeplikicookieInfo;
                }
            }

            /// <summary>
            /// The NavItem item.
            /// </summary>
            [RepositoryItem("48edf724-1806-440e-938b-77a9c66cb4c0")]
            public virtual Ranorex.LiTag NavItem
            {
                get
                {
                    return _navitemInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The NavItem item info.
            /// </summary>
            [RepositoryItemInfo("48edf724-1806-440e-938b-77a9c66cb4c0")]
            public virtual RepoItemInfo NavItemInfo
            {
                get
                {
                    return _navitemInfo;
                }
            }

            /// <summary>
            /// The Zamknij item.
            /// </summary>
            [RepositoryItem("a0fae0bc-55ec-43c4-b657-43d08560d722")]
            public virtual Ranorex.ATag Zamknij
            {
                get
                {
                    return _zamknijInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Zamknij item info.
            /// </summary>
            [RepositoryItemInfo("a0fae0bc-55ec-43c4-b657-43d08560d722")]
            public virtual RepoItemInfo ZamknijInfo
            {
                get
                {
                    return _zamknijInfo;
                }
            }

            /// <summary>
            /// The Submit1 item.
            /// </summary>
            [RepositoryItem("2cfb75a2-96bd-4e84-bc01-26c30c425ca0")]
            public virtual Ranorex.InputTag Submit1
            {
                get
                {
                    return _submit1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit1 item info.
            /// </summary>
            [RepositoryItemInfo("2cfb75a2-96bd-4e84-bc01-26c30c425ca0")]
            public virtual RepoItemInfo Submit1Info
            {
                get
                {
                    return _submit1Info;
                }
            }

            /// <summary>
            /// The NameError item.
            /// </summary>
            [RepositoryItem("5824f8a9-a2cc-40ea-91bd-204f3f90d7d5")]
            public virtual Ranorex.SpanTag NameError
            {
                get
                {
                    return _nameerrorInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The NameError item info.
            /// </summary>
            [RepositoryItemInfo("5824f8a9-a2cc-40ea-91bd-204f3f90d7d5")]
            public virtual RepoItemInfo NameErrorInfo
            {
                get
                {
                    return _nameerrorInfo;
                }
            }

            /// <summary>
            /// The EmailError item.
            /// </summary>
            [RepositoryItem("cc74656e-cc9b-4909-b0ae-12016589e824")]
            public virtual Ranorex.SpanTag EmailError
            {
                get
                {
                    return _emailerrorInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The EmailError item info.
            /// </summary>
            [RepositoryItemInfo("cc74656e-cc9b-4909-b0ae-12016589e824")]
            public virtual RepoItemInfo EmailErrorInfo
            {
                get
                {
                    return _emailerrorInfo;
                }
            }

            /// <summary>
            /// The PasswordError item.
            /// </summary>
            [RepositoryItem("84c91e27-6ce5-4c12-9d6a-cb68cca765f0")]
            public virtual Ranorex.SpanTag PasswordError
            {
                get
                {
                    return _passworderrorInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PasswordError item info.
            /// </summary>
            [RepositoryItemInfo("84c91e27-6ce5-4c12-9d6a-cb68cca765f0")]
            public virtual RepoItemInfo PasswordErrorInfo
            {
                get
                {
                    return _passworderrorInfo;
                }
            }

            /// <summary>
            /// The ConfirmPasswordError item.
            /// </summary>
            [RepositoryItem("c429f0e9-6ec2-4f79-9245-785e476d088b")]
            public virtual Ranorex.SpanTag ConfirmPasswordError
            {
                get
                {
                    return _confirmpassworderrorInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ConfirmPasswordError item info.
            /// </summary>
            [RepositoryItemInfo("c429f0e9-6ec2-4f79-9245-785e476d088b")]
            public virtual RepoItemInfo ConfirmPasswordErrorInfo
            {
                get
                {
                    return _confirmpassworderrorInfo;
                }
            }

            /// <summary>
            /// The GroupNameError item.
            /// </summary>
            [RepositoryItem("16c519b4-b599-4983-970c-31ef1c8c78f3")]
            public virtual Ranorex.SpanTag GroupNameError
            {
                get
                {
                    return _groupnameerrorInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GroupNameError item info.
            /// </summary>
            [RepositoryItemInfo("16c519b4-b599-4983-970c-31ef1c8c78f3")]
            public virtual RepoItemInfo GroupNameErrorInfo
            {
                get
                {
                    return _groupnameerrorInfo;
                }
            }

            /// <summary>
            /// The GroupPasswordError item.
            /// </summary>
            [RepositoryItem("c01d1c37-1065-4ef1-8fde-4b79b6537ac9")]
            public virtual Ranorex.SpanTag GroupPasswordError
            {
                get
                {
                    return _grouppassworderrorInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GroupPasswordError item info.
            /// </summary>
            [RepositoryItemInfo("c01d1c37-1065-4ef1-8fde-4b79b6537ac9")]
            public virtual RepoItemInfo GroupPasswordErrorInfo
            {
                get
                {
                    return _grouppassworderrorInfo;
                }
            }

            /// <summary>
            /// The Name item.
            /// </summary>
            [RepositoryItem("16dffdea-8194-4848-a1fd-e0b4caff8d3b")]
            public virtual Ranorex.InputTag Name
            {
                get
                {
                    return _nameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Name item info.
            /// </summary>
            [RepositoryItemInfo("16dffdea-8194-4848-a1fd-e0b4caff8d3b")]
            public virtual RepoItemInfo NameInfo
            {
                get
                {
                    return _nameInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("555f779d-8591-46cd-98d8-7a938b4f2b25")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("555f779d-8591-46cd-98d8-7a938b4f2b25")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("a0753bc4-a813-46a6-b17e-42721665eb9e")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("a0753bc4-a813-46a6-b17e-42721665eb9e")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The ConfirmPassword item.
            /// </summary>
            [RepositoryItem("9a3d6e44-2da3-438a-85e8-febe4d1cd26f")]
            public virtual Ranorex.InputTag ConfirmPassword
            {
                get
                {
                    return _confirmpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ConfirmPassword item info.
            /// </summary>
            [RepositoryItemInfo("9a3d6e44-2da3-438a-85e8-febe4d1cd26f")]
            public virtual RepoItemInfo ConfirmPasswordInfo
            {
                get
                {
                    return _confirmpasswordInfo;
                }
            }

            /// <summary>
            /// The GroupName item.
            /// </summary>
            [RepositoryItem("d836de61-74d7-4688-ac44-562f7849a78b")]
            public virtual Ranorex.InputTag GroupName
            {
                get
                {
                    return _groupnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The GroupName item info.
            /// </summary>
            [RepositoryItemInfo("d836de61-74d7-4688-ac44-562f7849a78b")]
            public virtual RepoItemInfo GroupNameInfo
            {
                get
                {
                    return _groupnameInfo;
                }
            }

            /// <summary>
            /// The GroupPassword item.
            /// </summary>
            [RepositoryItem("cfc5af30-4216-4f5d-aa9f-6114342b0fb4")]
            public virtual Ranorex.InputTag GroupPassword
            {
                get
                {
                    return _grouppasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The GroupPassword item info.
            /// </summary>
            [RepositoryItemInfo("cfc5af30-4216-4f5d-aa9f-6114342b0fb4")]
            public virtual RepoItemInfo GroupPasswordInfo
            {
                get
                {
                    return _grouppasswordInfo;
                }
            }

            /// <summary>
            /// The GroupConfirmPassword item.
            /// </summary>
            [RepositoryItem("264e39d3-92ba-479e-a754-46c255689803")]
            public virtual Ranorex.InputTag GroupConfirmPassword
            {
                get
                {
                    return _groupconfirmpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The GroupConfirmPassword item info.
            /// </summary>
            [RepositoryItemInfo("264e39d3-92ba-479e-a754-46c255689803")]
            public virtual RepoItemInfo GroupConfirmPasswordInfo
            {
                get
                {
                    return _groupconfirmpasswordInfo;
                }
            }

            /// <summary>
            /// The SubjectError item.
            /// </summary>
            [RepositoryItem("aae5de0b-36d0-449c-baf8-4be1efddb004")]
            public virtual Ranorex.SpanTag SubjectError
            {
                get
                {
                    return _subjecterrorInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SubjectError item info.
            /// </summary>
            [RepositoryItemInfo("aae5de0b-36d0-449c-baf8-4be1efddb004")]
            public virtual RepoItemInfo SubjectErrorInfo
            {
                get
                {
                    return _subjecterrorInfo;
                }
            }

            /// <summary>
            /// The MessageError item.
            /// </summary>
            [RepositoryItem("c20009e1-8a20-4c72-b518-86e9d2133cf6")]
            public virtual Ranorex.SpanTag MessageError
            {
                get
                {
                    return _messageerrorInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The MessageError item info.
            /// </summary>
            [RepositoryItemInfo("c20009e1-8a20-4c72-b518-86e9d2133cf6")]
            public virtual RepoItemInfo MessageErrorInfo
            {
                get
                {
                    return _messageerrorInfo;
                }
            }

            /// <summary>
            /// The Phone item.
            /// </summary>
            [RepositoryItem("b6157f17-0bd3-460b-a64c-0646e713a50d")]
            public virtual Ranorex.InputTag Phone
            {
                get
                {
                    return _phoneInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Phone item info.
            /// </summary>
            [RepositoryItemInfo("b6157f17-0bd3-460b-a64c-0646e713a50d")]
            public virtual RepoItemInfo PhoneInfo
            {
                get
                {
                    return _phoneInfo;
                }
            }

            /// <summary>
            /// The Subject item.
            /// </summary>
            [RepositoryItem("e928cf28-20d2-4667-834e-684ce06a63b8")]
            public virtual Ranorex.InputTag Subject
            {
                get
                {
                    return _subjectInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Subject item info.
            /// </summary>
            [RepositoryItemInfo("e928cf28-20d2-4667-834e-684ce06a63b8")]
            public virtual RepoItemInfo SubjectInfo
            {
                get
                {
                    return _subjectInfo;
                }
            }

            /// <summary>
            /// The Message item.
            /// </summary>
            [RepositoryItem("bf5c6af0-9d4e-41da-9a80-fbee6c34f2f6")]
            public virtual Ranorex.TextAreaTag Message
            {
                get
                {
                    return _messageInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The Message item info.
            /// </summary>
            [RepositoryItemInfo("bf5c6af0-9d4e-41da-9a80-fbee6c34f2f6")]
            public virtual RepoItemInfo MessageInfo
            {
                get
                {
                    return _messageInfo;
                }
            }

            /// <summary>
            /// The DziękujemyZaKontaktOdpiszemyNajszyb item.
            /// </summary>
            [RepositoryItem("cf5ea3cd-cbad-414a-9df0-e6f2d61161f3")]
            public virtual Ranorex.H4Tag DziękujemyZaKontaktOdpiszemyNajszyb
            {
                get
                {
                    return _dziękujemyzakontaktodpiszemynajszybInfo.CreateAdapter<Ranorex.H4Tag>(true);
                }
            }

            /// <summary>
            /// The DziękujemyZaKontaktOdpiszemyNajszyb item info.
            /// </summary>
            [RepositoryItemInfo("cf5ea3cd-cbad-414a-9df0-e6f2d61161f3")]
            public virtual RepoItemInfo DziękujemyZaKontaktOdpiszemyNajszybInfo
            {
                get
                {
                    return _dziękujemyzakontaktodpiszemynajszybInfo;
                }
            }

            /// <summary>
            /// The CreateNewGroup item.
            /// </summary>
            [RepositoryItem("ef699eab-8a4b-4695-9377-0fa8e179ca99")]
            public virtual Ranorex.InputTag CreateNewGroup
            {
                get
                {
                    return _createnewgroupInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CreateNewGroup item info.
            /// </summary>
            [RepositoryItemInfo("ef699eab-8a4b-4695-9377-0fa8e179ca99")]
            public virtual RepoItemInfo CreateNewGroupInfo
            {
                get
                {
                    return _createnewgroupInfo;
                }
            }

            /// <summary>
            /// The DivTagCol item.
            /// </summary>
            [RepositoryItem("865b39fd-6b42-4f4b-8b53-6af627f7172e")]
            public virtual Ranorex.DivTag DivTagCol
            {
                get
                {
                    return _divtagcolInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagCol item info.
            /// </summary>
            [RepositoryItemInfo("865b39fd-6b42-4f4b-8b53-6af627f7172e")]
            public virtual RepoItemInfo DivTagColInfo
            {
                get
                {
                    return _divtagcolInfo;
                }
            }

            /// <summary>
            /// The DivTagCol1 item.
            /// </summary>
            [RepositoryItem("cfa7a4cc-756a-4604-8b68-a6c793f8318d")]
            public virtual Ranorex.DivTag DivTagCol1
            {
                get
                {
                    return _divtagcol1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagCol1 item info.
            /// </summary>
            [RepositoryItemInfo("cfa7a4cc-756a-4604-8b68-a6c793f8318d")]
            public virtual RepoItemInfo DivTagCol1Info
            {
                get
                {
                    return _divtagcol1Info;
                }
            }

            /// <summary>
            /// The ButtonTag item.
            /// </summary>
            [RepositoryItem("692dcf19-4266-43fc-b7b7-d7dc825cc5f7")]
            public virtual Ranorex.InputTag ButtonTag
            {
                get
                {
                    return _buttontagInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTag item info.
            /// </summary>
            [RepositoryItemInfo("692dcf19-4266-43fc-b7b7-d7dc825cc5f7")]
            public virtual RepoItemInfo ButtonTagInfo
            {
                get
                {
                    return _buttontagInfo;
                }
            }

            /// <summary>
            /// The ButtonTag1 item.
            /// </summary>
            [RepositoryItem("3e991043-7423-4667-a8d9-9f6d1df70a8d")]
            public virtual Ranorex.ITag ButtonTag1
            {
                get
                {
                    return _buttontag1Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The ButtonTag1 item info.
            /// </summary>
            [RepositoryItemInfo("3e991043-7423-4667-a8d9-9f6d1df70a8d")]
            public virtual RepoItemInfo ButtonTag1Info
            {
                get
                {
                    return _buttontag1Info;
                }
            }

            /// <summary>
            /// The InputTagMac item.
            /// </summary>
            [RepositoryItem("67bf71cd-929b-4e45-a947-8c100889c2a8")]
            public virtual Ranorex.InputTag InputTagMac
            {
                get
                {
                    return _inputtagmacInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagMac item info.
            /// </summary>
            [RepositoryItemInfo("67bf71cd-929b-4e45-a947-8c100889c2a8")]
            public virtual RepoItemInfo InputTagMacInfo
            {
                get
                {
                    return _inputtagmacInfo;
                }
            }

            /// <summary>
            /// The Comment item.
            /// </summary>
            [RepositoryItem("f6cbe7b6-3133-408c-bdcf-ffc526678eab")]
            public virtual Ranorex.TextAreaTag Comment
            {
                get
                {
                    return _commentInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The Comment item info.
            /// </summary>
            [RepositoryItemInfo("f6cbe7b6-3133-408c-bdcf-ffc526678eab")]
            public virtual RepoItemInfo CommentInfo
            {
                get
                {
                    return _commentInfo;
                }
            }

            /// <summary>
            /// The Monday item.
            /// </summary>
            [RepositoryItem("d4e2a19e-b6fa-4beb-8fd7-6524d0d23aef")]
            public virtual Ranorex.InputTag Monday
            {
                get
                {
                    return _mondayInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Monday item info.
            /// </summary>
            [RepositoryItemInfo("d4e2a19e-b6fa-4beb-8fd7-6524d0d23aef")]
            public virtual RepoItemInfo MondayInfo
            {
                get
                {
                    return _mondayInfo;
                }
            }

            /// <summary>
            /// The DateEnd item.
            /// </summary>
            [RepositoryItem("d5b5a516-55b2-4a10-a709-8bd84342b1eb")]
            public virtual Ranorex.InputTag DateEnd
            {
                get
                {
                    return _dateendInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The DateEnd item info.
            /// </summary>
            [RepositoryItemInfo("d5b5a516-55b2-4a10-a709-8bd84342b1eb")]
            public virtual RepoItemInfo DateEndInfo
            {
                get
                {
                    return _dateendInfo;
                }
            }

            /// <summary>
            /// The DateStart item.
            /// </summary>
            [RepositoryItem("dd046d50-8421-4faf-962b-282474c73906")]
            public virtual Ranorex.InputTag DateStart
            {
                get
                {
                    return _datestartInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The DateStart item info.
            /// </summary>
            [RepositoryItemInfo("dd046d50-8421-4faf-962b-282474c73906")]
            public virtual RepoItemInfo DateStartInfo
            {
                get
                {
                    return _datestartInfo;
                }
            }

            /// <summary>
            /// The Repeat item.
            /// </summary>
            [RepositoryItem("195f1e99-9582-4ef1-8001-e8ba3f0d05be")]
            public virtual Ranorex.InputTag Repeat
            {
                get
                {
                    return _repeatInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Repeat item info.
            /// </summary>
            [RepositoryItemInfo("195f1e99-9582-4ef1-8001-e8ba3f0d05be")]
            public virtual RepoItemInfo RepeatInfo
            {
                get
                {
                    return _repeatInfo;
                }
            }

            /// <summary>
            /// The Wednesday item.
            /// </summary>
            [RepositoryItem("d1c7a0de-72c8-4744-8f1f-bc163b13aed1")]
            public virtual Ranorex.InputTag Wednesday
            {
                get
                {
                    return _wednesdayInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Wednesday item info.
            /// </summary>
            [RepositoryItemInfo("d1c7a0de-72c8-4744-8f1f-bc163b13aed1")]
            public virtual RepoItemInfo WednesdayInfo
            {
                get
                {
                    return _wednesdayInfo;
                }
            }

            /// <summary>
            /// The ButtonTag2 item.
            /// </summary>
            [RepositoryItem("161d428d-a548-44dd-bacc-a31c5ac754e7")]
            public virtual Ranorex.ATag ButtonTag2
            {
                get
                {
                    return _buttontag2Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ButtonTag2 item info.
            /// </summary>
            [RepositoryItemInfo("161d428d-a548-44dd-bacc-a31c5ac754e7")]
            public virtual RepoItemInfo ButtonTag2Info
            {
                get
                {
                    return _buttontag2Info;
                }
            }

            /// <summary>
            /// The DevicesOther item.
            /// </summary>
            [RepositoryItem("ef86b687-a6df-4643-bfe1-98dc10d132a6")]
            public virtual Ranorex.ITag DevicesOther
            {
                get
                {
                    return _devicesotherInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The DevicesOther item info.
            /// </summary>
            [RepositoryItemInfo("ef86b687-a6df-4643-bfe1-98dc10d132a6")]
            public virtual RepoItemInfo DevicesOtherInfo
            {
                get
                {
                    return _devicesotherInfo;
                }
            }

            /// <summary>
            /// The SomeATag item.
            /// </summary>
            [RepositoryItem("5e585588-7bb8-4842-828d-8264d2ff35e3")]
            public virtual Ranorex.ATag SomeATag
            {
                get
                {
                    return _someatagInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SomeATag item info.
            /// </summary>
            [RepositoryItemInfo("5e585588-7bb8-4842-828d-8264d2ff35e3")]
            public virtual RepoItemInfo SomeATagInfo
            {
                get
                {
                    return _someatagInfo;
                }
            }

            /// <summary>
            /// The DevicesOther1 item.
            /// </summary>
            [RepositoryItem("09f72e69-9e4e-4443-b42f-bf23afd95c06")]
            public virtual Ranorex.ITag DevicesOther1
            {
                get
                {
                    return _devicesother1Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The DevicesOther1 item info.
            /// </summary>
            [RepositoryItemInfo("09f72e69-9e4e-4443-b42f-bf23afd95c06")]
            public virtual RepoItemInfo DevicesOther1Info
            {
                get
                {
                    return _devicesother1Info;
                }
            }

            /// <summary>
            /// The FaFaPlus item.
            /// </summary>
            [RepositoryItem("ba7fcd07-678e-4893-b2a0-d5ed2e89b3db")]
            public virtual Ranorex.ITag FaFaPlus
            {
                get
                {
                    return _fafaplusInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FaFaPlus item info.
            /// </summary>
            [RepositoryItemInfo("ba7fcd07-678e-4893-b2a0-d5ed2e89b3db")]
            public virtual RepoItemInfo FaFaPlusInfo
            {
                get
                {
                    return _fafaplusInfo;
                }
            }

            /// <summary>
            /// The DeviceType item.
            /// </summary>
            [RepositoryItem("ecbb2e2f-a841-4c2a-b20a-0faa8e98deec")]
            public virtual Ranorex.SelectTag DeviceType
            {
                get
                {
                    return _devicetypeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The DeviceType item info.
            /// </summary>
            [RepositoryItemInfo("ecbb2e2f-a841-4c2a-b20a-0faa8e98deec")]
            public virtual RepoItemInfo DeviceTypeInfo
            {
                get
                {
                    return _devicetypeInfo;
                }
            }

            /// <summary>
            /// The DeviceId item.
            /// </summary>
            [RepositoryItem("facb4155-e1bc-491e-b22c-cfb47e598487")]
            public virtual Ranorex.SelectTag DeviceId
            {
                get
                {
                    return _deviceidInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The DeviceId item info.
            /// </summary>
            [RepositoryItemInfo("facb4155-e1bc-491e-b22c-cfb47e598487")]
            public virtual RepoItemInfo DeviceIdInfo
            {
                get
                {
                    return _deviceidInfo;
                }
            }

            /// <summary>
            /// The FaFaPlus1 item.
            /// </summary>
            [RepositoryItem("bdb6bbf3-35a9-435e-af43-f6281c595c0c")]
            public virtual Ranorex.ITag FaFaPlus1
            {
                get
                {
                    return _fafaplus1Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FaFaPlus1 item info.
            /// </summary>
            [RepositoryItemInfo("bdb6bbf3-35a9-435e-af43-f6281c595c0c")]
            public virtual RepoItemInfo FaFaPlus1Info
            {
                get
                {
                    return _fafaplus1Info;
                }
            }

            /// <summary>
            /// The Friday item.
            /// </summary>
            [RepositoryItem("60f9c6ad-fde5-4bda-9c60-9b181df23cb8")]
            public virtual Ranorex.InputTag Friday
            {
                get
                {
                    return _fridayInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Friday item info.
            /// </summary>
            [RepositoryItemInfo("60f9c6ad-fde5-4bda-9c60-9b181df23cb8")]
            public virtual RepoItemInfo FridayInfo
            {
                get
                {
                    return _fridayInfo;
                }
            }

            /// <summary>
            /// The Tuesday item.
            /// </summary>
            [RepositoryItem("551f5075-cafb-4839-b2f7-4236721a5c9e")]
            public virtual Ranorex.InputTag Tuesday
            {
                get
                {
                    return _tuesdayInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Tuesday item info.
            /// </summary>
            [RepositoryItemInfo("551f5075-cafb-4839-b2f7-4236721a5c9e")]
            public virtual RepoItemInfo TuesdayInfo
            {
                get
                {
                    return _tuesdayInfo;
                }
            }

            /// <summary>
            /// The DevicesOther2 item.
            /// </summary>
            [RepositoryItem("20b3938e-9b8d-4433-9859-1a4aff52464b")]
            public virtual Ranorex.ITag DevicesOther2
            {
                get
                {
                    return _devicesother2Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The DevicesOther2 item info.
            /// </summary>
            [RepositoryItemInfo("20b3938e-9b8d-4433-9859-1a4aff52464b")]
            public virtual RepoItemInfo DevicesOther2Info
            {
                get
                {
                    return _devicesother2Info;
                }
            }

            /// <summary>
            /// The DFlexJustifyContentCenterMb1Pt4 folder.
            /// </summary>
            [RepositoryFolder("b3a1e41c-84bc-4c7f-a4b6-21cf5344c79f")]
            public virtual WakeAppRepositoryFolders.DFlexJustifyContentCenterMb1Pt4Folder DFlexJustifyContentCenterMb1Pt4
            {
                get { return _dflexjustifycontentcentermb1pt4; }
            }

            /// <summary>
            /// The DivTagRow folder.
            /// </summary>
            [RepositoryFolder("5ddda5fd-8020-4a92-8a1d-7ca34811d11e")]
            public virtual WakeAppRepositoryFolders.DivTagRowFolder DivTagRow
            {
                get { return _divtagrow; }
            }
        }

        /// <summary>
        /// The DFlexJustifyContentCenterMb1Pt4Folder folder.
        /// </summary>
        [RepositoryFolder("b3a1e41c-84bc-4c7f-a4b6-21cf5344c79f")]
        public partial class DFlexJustifyContentCenterMb1Pt4Folder : RepoGenBaseFolder
        {
            RepoItemInfo _onasInfo;
            RepoItemInfo _politykaprywatnościInfo;
            RepoItemInfo _pomocInfo;
            RepoItemInfo _kontaktInfo;
            RepoItemInfo _fafagithubInfo;

            /// <summary>
            /// Creates a new DFlexJustifyContentCenterMb1Pt4  folder.
            /// </summary>
            public DFlexJustifyContentCenterMb1Pt4Folder(RepoGenBaseFolder parentFolder) :
                    base("DFlexJustifyContentCenterMb1Pt4", "?/?/footer/div/div[1]", parentFolder, 30000, null, false, "b3a1e41c-84bc-4c7f-a4b6-21cf5344c79f", "")
            {
                _onasInfo = new RepoItemInfo(this, "ONas", "div[1]/?/?/a[@innertext='O nas']", 30000, null, "2521d8fd-9d88-4c20-bbbe-4ef5a5ee858c");
                _politykaprywatnościInfo = new RepoItemInfo(this, "PolitykaPrywatności", "div[2]/?/?/a[@innertext='Polityka prywatności']", 30000, null, "f0e87bd2-38fd-4045-b6d4-47b58693ec1d");
                _pomocInfo = new RepoItemInfo(this, "Pomoc", "div[3]/?/?/a[@innertext='Pomoc']", 30000, null, "4397a601-4213-4857-a59f-a4e1ed4c25ab");
                _kontaktInfo = new RepoItemInfo(this, "Kontakt", "div[4]/?/?/a[@innertext='Kontakt']", 30000, null, "d83984be-0dd2-4bc7-8c90-fba6984e5f6b");
                _fafagithubInfo = new RepoItemInfo(this, "FaFaGithub", "div[5]/?/?/a[@title='github.com']/i", 30000, null, "f9413d29-204d-4f78-992d-5bd761648b9a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b3a1e41c-84bc-4c7f-a4b6-21cf5344c79f")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b3a1e41c-84bc-4c7f-a4b6-21cf5344c79f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ONas item.
            /// </summary>
            [RepositoryItem("2521d8fd-9d88-4c20-bbbe-4ef5a5ee858c")]
            public virtual Ranorex.ATag ONas
            {
                get
                {
                    return _onasInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ONas item info.
            /// </summary>
            [RepositoryItemInfo("2521d8fd-9d88-4c20-bbbe-4ef5a5ee858c")]
            public virtual RepoItemInfo ONasInfo
            {
                get
                {
                    return _onasInfo;
                }
            }

            /// <summary>
            /// The PolitykaPrywatności item.
            /// </summary>
            [RepositoryItem("f0e87bd2-38fd-4045-b6d4-47b58693ec1d")]
            public virtual Ranorex.ATag PolitykaPrywatności
            {
                get
                {
                    return _politykaprywatnościInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The PolitykaPrywatności item info.
            /// </summary>
            [RepositoryItemInfo("f0e87bd2-38fd-4045-b6d4-47b58693ec1d")]
            public virtual RepoItemInfo PolitykaPrywatnościInfo
            {
                get
                {
                    return _politykaprywatnościInfo;
                }
            }

            /// <summary>
            /// The Pomoc item.
            /// </summary>
            [RepositoryItem("4397a601-4213-4857-a59f-a4e1ed4c25ab")]
            public virtual Ranorex.ATag Pomoc
            {
                get
                {
                    return _pomocInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Pomoc item info.
            /// </summary>
            [RepositoryItemInfo("4397a601-4213-4857-a59f-a4e1ed4c25ab")]
            public virtual RepoItemInfo PomocInfo
            {
                get
                {
                    return _pomocInfo;
                }
            }

            /// <summary>
            /// The Kontakt item.
            /// </summary>
            [RepositoryItem("d83984be-0dd2-4bc7-8c90-fba6984e5f6b")]
            public virtual Ranorex.ATag Kontakt
            {
                get
                {
                    return _kontaktInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Kontakt item info.
            /// </summary>
            [RepositoryItemInfo("d83984be-0dd2-4bc7-8c90-fba6984e5f6b")]
            public virtual RepoItemInfo KontaktInfo
            {
                get
                {
                    return _kontaktInfo;
                }
            }

            /// <summary>
            /// The FaFaGithub item.
            /// </summary>
            [RepositoryItem("f9413d29-204d-4f78-992d-5bd761648b9a")]
            public virtual Ranorex.ITag FaFaGithub
            {
                get
                {
                    return _fafagithubInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FaFaGithub item info.
            /// </summary>
            [RepositoryItemInfo("f9413d29-204d-4f78-992d-5bd761648b9a")]
            public virtual RepoItemInfo FaFaGithubInfo
            {
                get
                {
                    return _fafagithubInfo;
                }
            }
        }

        /// <summary>
        /// The DivTagRowFolder folder.
        /// </summary>
        [RepositoryFolder("5ddda5fd-8020-4a92-8a1d-7ca34811d11e")]
        public partial class DivTagRowFolder : RepoGenBaseFolder
        {
            RepoItemInfo _wyślijInfo;
            RepoItemInfo _colmd4Info;
            RepoItemInfo _godzinypracyInfo;
            RepoItemInfo _wsparcietechniczneInfo;
            RepoItemInfo _podanyadresemailjużistnieje1Info;
            RepoItemInfo _submitInfo;
            RepoItemInfo _submit1Info;
            RepoItemInfo _submit2Info;
            RepoItemInfo _tdtagtestInfo;
            RepoItemInfo _atag1Info;
            RepoItemInfo _atagdodaj1Info;
            RepoItemInfo _sometdtagInfo;
            RepoItemInfo _proszęwybraćdatęzakończenianiewcześInfo;
            RepoItemInfo _tdtagInfo;
            RepoItemInfo _atag2Info;

            /// <summary>
            /// Creates a new DivTagRow  folder.
            /// </summary>
            public DivTagRowFolder(RepoGenBaseFolder parentFolder) :
                    base("DivTagRow", "body/div/?/?/section/div[1]", parentFolder, 30000, null, false, "5ddda5fd-8020-4a92-8a1d-7ca34811d11e", "")
            {
                _wyślijInfo = new RepoItemInfo(this, "Wyślij", ".//form[@action='http://www.projektbudzik.pl/Contact?']/div[7]/button[@innertext='Wyślij']", 30000, null, "0aaddfe7-2006-470d-a268-6067bc9418c8");
                _colmd4Info = new RepoItemInfo(this, "ColMd4", "div[2]/div[2]/div[1]", 30000, null, "4242ebae-4fa0-4ec9-973a-9dcb335e4686");
                _godzinypracyInfo = new RepoItemInfo(this, "GodzinyPracy", "div[2]/div[2]/div[2]/p[@innertext='Godziny pracy:']", 30000, null, "eae825a9-c8b7-4d96-ac49-c1ef8760651e");
                _wsparcietechniczneInfo = new RepoItemInfo(this, "WsparcieTechniczne", "div[2]/div[2]/div[3]/p[@innertext='Wsparcie Techniczne:']", 30000, null, "b96ea376-083a-474e-b327-f4270db5f603");
                _podanyadresemailjużistnieje1Info = new RepoItemInfo(this, "PodanyAdresEmailJużIstnieje1", ".//form[@action='http://www.projektbudzik.pl/Account/Register']/div[2]/span[@innertext>'Podany adres email już is']", 30000, null, "0212e189-751b-4c4e-97db-cdc605d2c6e1");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//form[@action='http://www.projektbudzik.pl/Account/Login']/div[3]/input[@type='submit']", 30000, null, "4ef233ab-e919-4674-865e-484e940acf6d");
                _submit1Info = new RepoItemInfo(this, "Submit1", ".//form[@action='http://www.projektbudzik.pl/Device/Create']/div[5]/input[@type='submit']", 30000, null, "01f2cc2e-8625-438a-b727-69e10a1cbe85");
                _submit2Info = new RepoItemInfo(this, "Submit2", ".//form[@action='http://www.projektbudzik.pl/Alarm/Create']/div[7]/input[@type='submit']", 30000, null, "5cf15ecb-5245-4e9b-ae98-1f8bc34f07f1");
                _tdtagtestInfo = new RepoItemInfo(this, "TdTagTest", "table/tbody/tr/td[6]", 30000, null, "1ab4cfa0-5176-44f8-843d-d755cfdb5891");
                _atag1Info = new RepoItemInfo(this, "ATag1", "table/tbody/tr/td[5]/?/?/a[@a='']", 30000, null, "b862abe1-d010-484f-be58-6ed144a5c575");
                _atagdodaj1Info = new RepoItemInfo(this, "ATagDodaj1", "?/?/a[@innertext>'                Dodaj']", 30000, null, "24a74b30-baf0-4e0f-bf89-a0db0fb1287e");
                _sometdtagInfo = new RepoItemInfo(this, "SomeTdTag", "table/tbody/tr[2]/td[1]", 30000, null, "a1298bf2-83a9-4d67-a0f5-b42b108e00a2");
                _proszęwybraćdatęzakończenianiewcześInfo = new RepoItemInfo(this, "ProszęWybraćDatęZakończeniaNieWcześ", ".//form[@action='http://www.projektbudzik.pl/Alarm/Create']/div[5]/?/?/span[@innertext>'Proszę wybrać datę zakończenia']", 30000, null, "a8d87bbe-836b-4e8b-b03a-e76d1d182f8f");
                _tdtagInfo = new RepoItemInfo(this, "TdTag", "table/tbody/?/?/td[@innertext>'                        12']", 30000, null, "550c2525-4d86-4bec-af76-6b234c6b6685");
                _atag2Info = new RepoItemInfo(this, "ATag2", "table/tbody/tr[1]/td[4]/?/?/a[@innertext>'']", 30000, null, "f4d173be-cf82-4b74-9c20-ce513b13bcd5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5ddda5fd-8020-4a92-8a1d-7ca34811d11e")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5ddda5fd-8020-4a92-8a1d-7ca34811d11e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Wyślij item.
            /// </summary>
            [RepositoryItem("0aaddfe7-2006-470d-a268-6067bc9418c8")]
            public virtual Ranorex.ButtonTag Wyślij
            {
                get
                {
                    return _wyślijInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Wyślij item info.
            /// </summary>
            [RepositoryItemInfo("0aaddfe7-2006-470d-a268-6067bc9418c8")]
            public virtual RepoItemInfo WyślijInfo
            {
                get
                {
                    return _wyślijInfo;
                }
            }

            /// <summary>
            /// The ColMd4 item.
            /// </summary>
            [RepositoryItem("4242ebae-4fa0-4ec9-973a-9dcb335e4686")]
            public virtual Ranorex.DivTag ColMd4
            {
                get
                {
                    return _colmd4Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ColMd4 item info.
            /// </summary>
            [RepositoryItemInfo("4242ebae-4fa0-4ec9-973a-9dcb335e4686")]
            public virtual RepoItemInfo ColMd4Info
            {
                get
                {
                    return _colmd4Info;
                }
            }

            /// <summary>
            /// The GodzinyPracy item.
            /// </summary>
            [RepositoryItem("eae825a9-c8b7-4d96-ac49-c1ef8760651e")]
            public virtual Ranorex.PTag GodzinyPracy
            {
                get
                {
                    return _godzinypracyInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The GodzinyPracy item info.
            /// </summary>
            [RepositoryItemInfo("eae825a9-c8b7-4d96-ac49-c1ef8760651e")]
            public virtual RepoItemInfo GodzinyPracyInfo
            {
                get
                {
                    return _godzinypracyInfo;
                }
            }

            /// <summary>
            /// The WsparcieTechniczne item.
            /// </summary>
            [RepositoryItem("b96ea376-083a-474e-b327-f4270db5f603")]
            public virtual Ranorex.PTag WsparcieTechniczne
            {
                get
                {
                    return _wsparcietechniczneInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The WsparcieTechniczne item info.
            /// </summary>
            [RepositoryItemInfo("b96ea376-083a-474e-b327-f4270db5f603")]
            public virtual RepoItemInfo WsparcieTechniczneInfo
            {
                get
                {
                    return _wsparcietechniczneInfo;
                }
            }

            /// <summary>
            /// The PodanyAdresEmailJużIstnieje1 item.
            /// </summary>
            [RepositoryItem("0212e189-751b-4c4e-97db-cdc605d2c6e1")]
            public virtual Ranorex.SpanTag PodanyAdresEmailJużIstnieje1
            {
                get
                {
                    return _podanyadresemailjużistnieje1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PodanyAdresEmailJużIstnieje1 item info.
            /// </summary>
            [RepositoryItemInfo("0212e189-751b-4c4e-97db-cdc605d2c6e1")]
            public virtual RepoItemInfo PodanyAdresEmailJużIstnieje1Info
            {
                get
                {
                    return _podanyadresemailjużistnieje1Info;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("4ef233ab-e919-4674-865e-484e940acf6d")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("4ef233ab-e919-4674-865e-484e940acf6d")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The Submit1 item.
            /// </summary>
            [RepositoryItem("01f2cc2e-8625-438a-b727-69e10a1cbe85")]
            public virtual Ranorex.InputTag Submit1
            {
                get
                {
                    return _submit1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit1 item info.
            /// </summary>
            [RepositoryItemInfo("01f2cc2e-8625-438a-b727-69e10a1cbe85")]
            public virtual RepoItemInfo Submit1Info
            {
                get
                {
                    return _submit1Info;
                }
            }

            /// <summary>
            /// The Submit2 item.
            /// </summary>
            [RepositoryItem("5cf15ecb-5245-4e9b-ae98-1f8bc34f07f1")]
            public virtual Ranorex.InputTag Submit2
            {
                get
                {
                    return _submit2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit2 item info.
            /// </summary>
            [RepositoryItemInfo("5cf15ecb-5245-4e9b-ae98-1f8bc34f07f1")]
            public virtual RepoItemInfo Submit2Info
            {
                get
                {
                    return _submit2Info;
                }
            }

            /// <summary>
            /// The TdTagTest item.
            /// </summary>
            [RepositoryItem("1ab4cfa0-5176-44f8-843d-d755cfdb5891")]
            public virtual Ranorex.TdTag TdTagTest
            {
                get
                {
                    return _tdtagtestInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The TdTagTest item info.
            /// </summary>
            [RepositoryItemInfo("1ab4cfa0-5176-44f8-843d-d755cfdb5891")]
            public virtual RepoItemInfo TdTagTestInfo
            {
                get
                {
                    return _tdtagtestInfo;
                }
            }

            /// <summary>
            /// The ATag1 item.
            /// </summary>
            [RepositoryItem("b862abe1-d010-484f-be58-6ed144a5c575")]
            public virtual Ranorex.ATag ATag1
            {
                get
                {
                    return _atag1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATag1 item info.
            /// </summary>
            [RepositoryItemInfo("b862abe1-d010-484f-be58-6ed144a5c575")]
            public virtual RepoItemInfo ATag1Info
            {
                get
                {
                    return _atag1Info;
                }
            }

            /// <summary>
            /// The ATagDodaj1 item.
            /// </summary>
            [RepositoryItem("24a74b30-baf0-4e0f-bf89-a0db0fb1287e")]
            public virtual Ranorex.ATag ATagDodaj1
            {
                get
                {
                    return _atagdodaj1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagDodaj1 item info.
            /// </summary>
            [RepositoryItemInfo("24a74b30-baf0-4e0f-bf89-a0db0fb1287e")]
            public virtual RepoItemInfo ATagDodaj1Info
            {
                get
                {
                    return _atagdodaj1Info;
                }
            }

            /// <summary>
            /// The SomeTdTag item.
            /// </summary>
            [RepositoryItem("a1298bf2-83a9-4d67-a0f5-b42b108e00a2")]
            public virtual Ranorex.TdTag SomeTdTag
            {
                get
                {
                    return _sometdtagInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The SomeTdTag item info.
            /// </summary>
            [RepositoryItemInfo("a1298bf2-83a9-4d67-a0f5-b42b108e00a2")]
            public virtual RepoItemInfo SomeTdTagInfo
            {
                get
                {
                    return _sometdtagInfo;
                }
            }

            /// <summary>
            /// The ProszęWybraćDatęZakończeniaNieWcześ item.
            /// </summary>
            [RepositoryItem("a8d87bbe-836b-4e8b-b03a-e76d1d182f8f")]
            public virtual Ranorex.SpanTag ProszęWybraćDatęZakończeniaNieWcześ
            {
                get
                {
                    return _proszęwybraćdatęzakończenianiewcześInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ProszęWybraćDatęZakończeniaNieWcześ item info.
            /// </summary>
            [RepositoryItemInfo("a8d87bbe-836b-4e8b-b03a-e76d1d182f8f")]
            public virtual RepoItemInfo ProszęWybraćDatęZakończeniaNieWcześInfo
            {
                get
                {
                    return _proszęwybraćdatęzakończenianiewcześInfo;
                }
            }

            /// <summary>
            /// The TdTag item.
            /// </summary>
            [RepositoryItem("550c2525-4d86-4bec-af76-6b234c6b6685")]
            public virtual Ranorex.TdTag TdTag
            {
                get
                {
                    return _tdtagInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The TdTag item info.
            /// </summary>
            [RepositoryItemInfo("550c2525-4d86-4bec-af76-6b234c6b6685")]
            public virtual RepoItemInfo TdTagInfo
            {
                get
                {
                    return _tdtagInfo;
                }
            }

            /// <summary>
            /// The ATag2 item.
            /// </summary>
            [RepositoryItem("f4d173be-cf82-4b74-9c20-ce513b13bcd5")]
            public virtual Ranorex.ATag ATag2
            {
                get
                {
                    return _atag2Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATag2 item info.
            /// </summary>
            [RepositoryItemInfo("f4d173be-cf82-4b74-9c20-ce513b13bcd5")]
            public virtual RepoItemInfo ATag2Info
            {
                get
                {
                    return _atag2Info;
                }
            }
        }

        /// <summary>
        /// The BrowserAppFolder folder.
        /// </summary>
        [RepositoryFolder("7855513f-a5aa-42d6-b5ea-7ef3d15754d4")]
        public partial class BrowserAppFolder : RepoGenBaseFolder
        {
            WakeAppRepositoryFolders.DomAppFolder _dom;

            /// <summary>
            /// Creates a new Browser  folder.
            /// </summary>
            public BrowserAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Browser", "/mobileapp[@title='ranorex.RxBrowser']", parentFolder, 10000, null, false, "7855513f-a5aa-42d6-b5ea-7ef3d15754d4", "")
            {
                _dom = new WakeAppRepositoryFolders.DomAppFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7855513f-a5aa-42d6-b5ea-7ef3d15754d4")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7855513f-a5aa-42d6-b5ea-7ef3d15754d4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Dom folder.
            /// </summary>
            [RepositoryFolder("1c6d52a2-0346-48f1-8157-72884aebb352")]
            public virtual WakeAppRepositoryFolders.DomAppFolder Dom
            {
                get { return _dom; }
            }
        }

        /// <summary>
        /// The DomAppFolder folder.
        /// </summary>
        [RepositoryFolder("1c6d52a2-0346-48f1-8157-72884aebb352")]
        public partial class DomAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dom  folder.
            /// </summary>
            public DomAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dom", ".//dom", parentFolder, 10000, null, false, "1c6d52a2-0346-48f1-8157-72884aebb352", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1c6d52a2-0346-48f1-8157-72884aebb352")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1c6d52a2-0346-48f1-8157-72884aebb352")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("bedc4ef0-6b21-4e8b-b20c-72a1e3ae491d")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "bedc4ef0-6b21-4e8b-b20c-72a1e3ae491d", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bedc4ef0-6b21-4e8b-b20c-72a1e3ae491d")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bedc4ef0-6b21-4e8b-b20c-72a1e3ae491d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
